// @generated by cargo run -p plurora-cli --bin generate-sdks
// Rust client methods generated from docs/spec/v1/schemas/methods/.
use crate::client::PluroraClient;
use crate::types::*;
use anyhow::Result;
impl PluroraClient {
    pub async fn authority_decision_list(
        &self,
        params: EmptyParams,
    ) -> Result<AuthorityDecisionListResult> {
        let raw = self
            .invoke("authority.decision.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_grant_create(
        &self,
        params: PermissionGrantParams,
    ) -> Result<PermissionGrantRecord> {
        let raw = self
            .invoke("authority.grant.create", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_grant_list(
        &self,
        params: PermissionListParams,
    ) -> Result<AuthorityGrantListResult> {
        let raw = self
            .invoke("authority.grant.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_grant_revoke(
        &self,
        params: PermissionRevokeParams,
    ) -> Result<PermissionGrantRecord> {
        let raw = self
            .invoke("authority.grant.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_handle_attenuate(
        &self,
        params: CapAttenuateParams,
    ) -> Result<CapHandleResult> {
        let raw = self
            .invoke("authority.handle.attenuate", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_handle_list(
        &self,
        params: CapListForParams,
    ) -> Result<CapHandlesResult> {
        let raw = self
            .invoke("authority.handle.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn authority_handle_revoke(
        &self,
        params: CapRevokeParams,
    ) -> Result<AuthorityHandleRevokeResult> {
        let raw = self
            .invoke("authority.handle.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_cancel(
        &self,
        params: CapabilityCancelParams,
    ) -> Result<StreamFrameEnvelope> {
        let raw = self
            .invoke("capability.cancel", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_describe(
        &self,
        params: EmptyParams,
    ) -> Result<CapabilityDescribeResult> {
        let raw = self
            .invoke("capability.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_discover(
        &self,
        params: EmptyParams,
    ) -> Result<CapabilityDiscoverResult> {
        let raw = self
            .invoke("capability.discover", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_invoke(
        &self,
        params: CapabilityInvocationRequest,
    ) -> Result<CapabilityInvocationResult> {
        let raw = self
            .invoke("capability.invoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn capability_stream(
        &self,
        params: CapabilityStreamParams,
    ) -> Result<CapabilityStreamResult> {
        let raw = self
            .invoke("capability.stream", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_apply(&self, params: ProposalIdParams) -> Result<ProposalRecord> {
        let raw = self
            .invoke("change.proposal.apply", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_approve(
        &self,
        params: ProposalDecisionParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .invoke("change.proposal.approve", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_create(&self, params: ProposalRecord) -> Result<ProposalRecord> {
        let raw = self
            .invoke("change.proposal.create", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_get(&self, params: ProposalIdParams) -> Result<ProposalRecord> {
        let raw = self
            .invoke("change.proposal.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_list(
        &self,
        params: EmptyParams,
    ) -> Result<ChangeProposalListResult> {
        let raw = self
            .invoke("change.proposal.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn change_proposal_reject(
        &self,
        params: ProposalDecisionParams,
    ) -> Result<ProposalRecord> {
        let raw = self
            .invoke("change.proposal.reject", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_branch_list(
        &self,
        params: SessionBranchListParams,
    ) -> Result<ContextBranchListResult> {
        let raw = self
            .invoke("context.branch.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_close(&self, params: SessionCloseParams) -> Result<EventEnvelope> {
        let raw = self
            .invoke("context.close", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_fork(&self, params: SessionForkParams) -> Result<BranchRecord> {
        let raw = self
            .invoke("context.fork", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_get(&self, params: SessionGetParams) -> Result<SessionRecord> {
        let raw = self
            .invoke("context.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_list(&self, params: EmptyParams) -> Result<ContextListResult> {
        let raw = self
            .invoke("context.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn context_open(&self, params: OpenSessionRequest) -> Result<SessionRecord> {
        let raw = self
            .invoke("context.open", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_binding_candidates(
        &self,
        params: BindingCandidatesRequest,
    ) -> Result<BindingCandidatesResult> {
        let raw = self
            .invoke("host.binding.candidates", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_binding_list(
        &self,
        params: BindingListRequest,
    ) -> Result<HostBindingListResult> {
        let raw = self
            .invoke("host.binding.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_binding_revoke(
        &self,
        params: BindingRevokeRequest,
    ) -> Result<BindingMutationResult> {
        let raw = self
            .invoke("host.binding.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_binding_select(
        &self,
        params: BindingSelectRequest,
    ) -> Result<BindingMutationResult> {
        let raw = self
            .invoke("host.binding.select", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_diagnostics(&self, params: EmptyParams) -> Result<HostDiagnosticsResult> {
        let raw = self
            .invoke("host.diagnostics", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exec_list(&self, params: EmptyParams) -> Result<LocalExecListResponse> {
        let raw = self
            .invoke("host.exec.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exec_logs(
        &self,
        params: LocalExecLogsRequest,
    ) -> Result<LocalExecLogsResponse> {
        let raw = self
            .invoke("host.exec.logs", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exec_start(
        &self,
        params: LocalExecStartRequest,
    ) -> Result<LocalExecStartResponse> {
        let raw = self
            .invoke("host.exec.start", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exec_status(&self, params: ExecIdParams) -> Result<LocalExecStatusResponse> {
        let raw = self
            .invoke("host.exec.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exec_stop(
        &self,
        params: LocalExecStopRequest,
    ) -> Result<LocalExecStopResponse> {
        let raw = self
            .invoke("host.exec.stop", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exposure_create(
        &self,
        params: ExposureCreateRequest,
    ) -> Result<ExposureMutationResult> {
        let raw = self
            .invoke("host.exposure.create", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exposure_list(
        &self,
        params: ExposureListRequest,
    ) -> Result<HostExposureListResult> {
        let raw = self
            .invoke("host.exposure.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_exposure_revoke(
        &self,
        params: ExposureRevokeRequest,
    ) -> Result<ExposureMutationResult> {
        let raw = self
            .invoke("host.exposure.revoke", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_info(&self, params: EmptyParams) -> Result<HostInfo> {
        let raw = self
            .invoke("host.info", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_installation_create(
        &self,
        params: InstallationCreateRequest,
    ) -> Result<InstallationMutationResult> {
        let raw = self
            .invoke("host.installation.create", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_installation_get(
        &self,
        params: InstallationGetRequest,
    ) -> Result<InstallationView> {
        let raw = self
            .invoke("host.installation.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_installation_list(
        &self,
        params: InstallationListRequest,
    ) -> Result<HostInstallationListResult> {
        let raw = self
            .invoke("host.installation.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_installation_remove(
        &self,
        params: InstallationRemoveRequest,
    ) -> Result<InstallationMutationResult> {
        let raw = self
            .invoke("host.installation.remove", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_installation_update(
        &self,
        params: InstallationUpdateRequest,
    ) -> Result<InstallationMutationResult> {
        let raw = self
            .invoke("host.installation.update", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_audit(
        &self,
        params: OutboundAuditParams,
    ) -> Result<HostOutboundAuditResult> {
        let raw = self
            .invoke("host.outbound.audit", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_execute(
        &self,
        params: OutboundExecuteParams,
    ) -> Result<OutboundExecutorResponse> {
        let raw = self
            .invoke("host.outbound.execute", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_stream(
        &self,
        params: OutboundStreamParams,
    ) -> Result<OutboundStreamResponse> {
        let raw = self
            .invoke("host.outbound.stream", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_websocket_close(
        &self,
        params: OutboundWebSocketSendParams,
    ) -> Result<HostOutboundWebsocketCloseResult> {
        let raw = self
            .invoke(
                "host.outbound.websocket.close",
                serde_json::to_value(params)?,
            )
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_websocket_open(
        &self,
        params: OutboundWebSocketOpenRequest,
    ) -> Result<HostOutboundWebsocketOpenResult> {
        let raw = self
            .invoke(
                "host.outbound.websocket.open",
                serde_json::to_value(params)?,
            )
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_outbound_websocket_send(
        &self,
        params: OutboundWebSocketSendParams,
    ) -> Result<HostOutboundWebsocketSendResult> {
        let raw = self
            .invoke(
                "host.outbound.websocket.send",
                serde_json::to_value(params)?,
            )
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_audit(
        &self,
        params: AuditPackageParams,
    ) -> Result<PackageAuditReport> {
        let raw = self
            .invoke("host.package.audit", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_describe(
        &self,
        params: EmptyParams,
    ) -> Result<HostPackageDescribeResult> {
        let raw = self
            .invoke("host.package.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_list(&self, params: EmptyParams) -> Result<HostPackageListResult> {
        let raw = self
            .invoke("host.package.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_load(&self, params: PackageManifest) -> Result<PackageRecord> {
        let raw = self
            .invoke("host.package.load", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_logs(
        &self,
        params: PackageIdParams,
    ) -> Result<HostPackageLogsResult> {
        let raw = self
            .invoke("host.package.logs", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_restart(&self, params: PackageIdParams) -> Result<PackageRecord> {
        let raw = self
            .invoke("host.package.restart", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_status(&self, params: PackageIdParams) -> Result<PackageRecord> {
        let raw = self
            .invoke("host.package.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_package_unload(&self, params: PackageIdParams) -> Result<PackageRecord> {
        let raw = self
            .invoke("host.package.unload", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_ping(&self, params: EmptyParams) -> Result<HostPingResult> {
        let raw = self
            .invoke("host.ping", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_port_lease(&self, params: PortLeaseRequest) -> Result<PortLeaseResponse> {
        let raw = self
            .invoke("host.port.lease", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_port_list(&self, params: EmptyParams) -> Result<HostPortListResult> {
        let raw = self
            .invoke("host.port.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_port_release(&self, params: PortLeaseIdParams) -> Result<PortLeaseRecord> {
        let raw = self
            .invoke("host.port.release", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_port_status(&self, params: PortLeaseIdParams) -> Result<PortLeaseRecord> {
        let raw = self
            .invoke("host.port.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_proxy_list(&self, params: EmptyParams) -> Result<HostProxyListResult> {
        let raw = self
            .invoke("host.proxy.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_proxy_register(
        &self,
        params: ProxyRouteRegisterRequest,
    ) -> Result<ProxyRouteRegisterResponse> {
        let raw = self
            .invoke("host.proxy.register", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_proxy_status(&self, params: ProxyRouteIdParams) -> Result<ProxyRouteRecord> {
        let raw = self
            .invoke("host.proxy.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_proxy_unregister(
        &self,
        params: ProxyRouteIdParams,
    ) -> Result<ProxyRouteRecord> {
        let raw = self
            .invoke("host.proxy.unregister", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_run_get(&self, params: RunGetRequest) -> Result<RunView> {
        let raw = self
            .invoke("host.run.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_run_list(&self, params: RunListRequest) -> Result<HostRunListResult> {
        let raw = self
            .invoke("host.run.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_run_start(&self, params: RunStartRequest) -> Result<RunStartResult> {
        let raw = self
            .invoke("host.run.start", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_run_status(&self, params: RunStatusRequest) -> Result<RunStatusView> {
        let raw = self
            .invoke("host.run.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_run_stop(&self, params: RunStopRequest) -> Result<RunMutationResult> {
        let raw = self
            .invoke("host.run.stop", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_surface_bundle_resolve(
        &self,
        params: SurfaceResolveBundleParams,
    ) -> Result<SurfaceResolveBundleResult> {
        let raw = self
            .invoke("host.surface.bundle.resolve", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_target_list(&self, params: EmptyParams) -> Result<HostTargetListResult> {
        let raw = self
            .invoke("host.target.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_target_register(&self, params: ExecutionTarget) -> Result<ExecutionTarget> {
        let raw = self
            .invoke("host.target.register", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_target_status(&self, params: TargetIdParams) -> Result<ExecutionTarget> {
        let raw = self
            .invoke("host.target.status", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn host_target_unregister(&self, params: TargetIdParams) -> Result<ExecutionTarget> {
        let raw = self
            .invoke("host.target.unregister", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn identity_current(&self, params: EmptyParams) -> Result<IdentityCurrentResult> {
        let raw = self
            .invoke("identity.current", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn journal_append(&self, params: AppendEventRequest) -> Result<EventEnvelope> {
        let raw = self
            .invoke("journal.append", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn journal_list(&self, params: EventListRequest) -> Result<JournalListResult> {
        let raw = self
            .invoke("journal.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn journal_subscribe(&self, params: EmptyParams) -> Result<JournalSubscribeResult> {
        let raw = self
            .invoke("journal.subscribe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn object_get(&self, params: ObjectGetRequest) -> Result<ObjectGetResponse> {
        let raw = self
            .invoke("object.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn object_list(&self, params: EmptyParams) -> Result<ObjectListResult> {
        let raw = self
            .invoke("object.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn object_put(&self, params: AssetPutRequest) -> Result<ObjectPutResponse> {
        let raw = self
            .invoke("object.put", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_get(&self, params: ProjectionIdParams) -> Result<ProjectionDefinition> {
        let raw = self
            .invoke("projection.get", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_list(&self, params: EmptyParams) -> Result<ProjectionListResult> {
        let raw = self
            .invoke("projection.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_rebuild(
        &self,
        params: ProjectionIdParams,
    ) -> Result<ProjectionDefinition> {
        let raw = self
            .invoke("projection.rebuild", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn projection_register(
        &self,
        params: ProjectionDefinition,
    ) -> Result<ProjectionDefinition> {
        let raw = self
            .invoke("projection.register", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn protocol_extension_describe(
        &self,
        params: EmptyParams,
    ) -> Result<ProtocolExtensionDescribeResult> {
        let raw = self
            .invoke("protocol.extension.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn protocol_extension_list(
        &self,
        params: EmptyParams,
    ) -> Result<ProtocolExtensionListResult> {
        let raw = self
            .invoke("protocol.extension.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn protocol_hook_list(&self, params: EmptyParams) -> Result<ProtocolHookListResult> {
        let raw = self
            .invoke("protocol.hook.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn shell_contribution_describe(
        &self,
        params: SurfaceDescribeParams,
    ) -> Result<ShellContributionDescribeResult> {
        let raw = self
            .invoke("shell.contribution.describe", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
    pub async fn shell_contribution_list(
        &self,
        params: SurfaceListParams,
    ) -> Result<ShellContributionListResult> {
        let raw = self
            .invoke("shell.contribution.list", serde_json::to_value(params)?)
            .await?;
        Ok(serde_json::from_value(raw)?)
    }
}
