import type {
  AcquisitionRecord as GeneratedAcquisitionRecord,
  InstallationCreateRequest as GeneratedInstallationCreateRequest,
  InstallationDiff as GeneratedInstallationDiff,
  InstallationMutationResult as GeneratedInstallationMutationResult,
  InstallationRecord as GeneratedInstallationRecord,
  InstallationRemoveRequest as GeneratedInstallationRemoveRequest,
  InstallationRollbackPointer as GeneratedInstallationRollbackPointer,
  InstallationSecretPolicy as GeneratedInstallationSecretPolicy,
  InstallationStateAction as GeneratedInstallationStateAction,
  InstallationUpdateRequest as GeneratedInstallationUpdateRequest,
  InstallationView as GeneratedInstallationView,
  StateAction as GeneratedStateAction,
  StateBindingRecord as GeneratedStateBindingRecord,
  WorkId as GeneratedWorkId,
  HostRunListResult as GeneratedHostRunListResult,
  RunGetRequest as GeneratedRunGetRequest,
  RunListRequest as GeneratedRunListRequest,
  RunMutationResult as GeneratedRunMutationResult,
  RunStartRequest as GeneratedRunStartRequest,
  RunStartResult as GeneratedRunStartResult,
  RunStatusRequest as GeneratedRunStatusRequest,
  RunStatusView as GeneratedRunStatusView,
  RunStopRequest as GeneratedRunStopRequest,
  RunView as GeneratedRunView,
} from "../../../../sdk/typescript/contract-sdk/src/types";
import type {
  AcquisitionRecord,
  InstallationCreateRequest,
  InstallationDiff,
  InstallationMutationResult,
  InstallationRecord,
  InstallationRemoveRequest,
  InstallationRollbackPointer,
  InstallationSecretPolicy,
  InstallationStateAction,
  InstallationUpdateRequest,
  InstallationView,
  StateAction,
  StateBindingRecord,
  WorkId,
  HostRunListResult,
  RunGetRequest,
  RunListRequest,
  RunMutationResult,
  RunStartRequest,
  RunStartResult,
  RunStatusRequest,
  RunStatusView,
  RunStopRequest,
  RunView,
} from "./client";

type Assert<T extends true> = T;
type Extends<From, To> = [From] extends [To] ? true : false;

type WebToGenerated = [
  Assert<Extends<AcquisitionRecord, GeneratedAcquisitionRecord>>,
  Assert<Extends<InstallationCreateRequest, GeneratedInstallationCreateRequest>>,
  Assert<Extends<InstallationDiff, GeneratedInstallationDiff>>,
  Assert<Extends<InstallationMutationResult, GeneratedInstallationMutationResult>>,
  Assert<Extends<InstallationRecord, GeneratedInstallationRecord>>,
  Assert<Extends<InstallationRemoveRequest, GeneratedInstallationRemoveRequest>>,
  Assert<Extends<InstallationRollbackPointer, GeneratedInstallationRollbackPointer>>,
  Assert<Extends<InstallationSecretPolicy, GeneratedInstallationSecretPolicy>>,
  Assert<Extends<InstallationStateAction, GeneratedInstallationStateAction>>,
  Assert<Extends<InstallationUpdateRequest, GeneratedInstallationUpdateRequest>>,
  Assert<Extends<InstallationView, GeneratedInstallationView>>,
  Assert<Extends<StateAction, GeneratedStateAction>>,
  Assert<Extends<StateBindingRecord, GeneratedStateBindingRecord>>,
  Assert<Extends<WorkId, GeneratedWorkId>>,
  Assert<Extends<HostRunListResult, GeneratedHostRunListResult>>,
  Assert<Extends<RunGetRequest, GeneratedRunGetRequest>>,
  Assert<Extends<RunListRequest, GeneratedRunListRequest>>,
  Assert<Extends<RunMutationResult, GeneratedRunMutationResult>>,
  Assert<Extends<RunStartRequest, GeneratedRunStartRequest>>,
  Assert<Extends<RunStartResult, GeneratedRunStartResult>>,
  Assert<Extends<RunStatusRequest, GeneratedRunStatusRequest>>,
  Assert<Extends<RunStatusView, GeneratedRunStatusView>>,
  Assert<Extends<RunStopRequest, GeneratedRunStopRequest>>,
  Assert<Extends<RunView, GeneratedRunView>>,
];

type GeneratedToWeb = [
  Assert<Extends<GeneratedAcquisitionRecord, AcquisitionRecord>>,
  Assert<Extends<GeneratedInstallationCreateRequest, InstallationCreateRequest>>,
  Assert<Extends<GeneratedInstallationDiff, InstallationDiff>>,
  Assert<Extends<GeneratedInstallationMutationResult, InstallationMutationResult>>,
  Assert<Extends<GeneratedInstallationRecord, InstallationRecord>>,
  Assert<Extends<GeneratedInstallationRemoveRequest, InstallationRemoveRequest>>,
  Assert<Extends<GeneratedInstallationRollbackPointer, InstallationRollbackPointer>>,
  Assert<Extends<GeneratedInstallationSecretPolicy, InstallationSecretPolicy>>,
  Assert<Extends<GeneratedInstallationStateAction, InstallationStateAction>>,
  Assert<Extends<GeneratedInstallationUpdateRequest, InstallationUpdateRequest>>,
  Assert<Extends<GeneratedInstallationView, InstallationView>>,
  Assert<Extends<GeneratedStateAction, StateAction>>,
  Assert<Extends<GeneratedStateBindingRecord, StateBindingRecord>>,
  Assert<Extends<GeneratedWorkId, WorkId>>,
  Assert<Extends<GeneratedHostRunListResult, HostRunListResult>>,
  Assert<Extends<GeneratedRunGetRequest, RunGetRequest>>,
  Assert<Extends<GeneratedRunListRequest, RunListRequest>>,
  Assert<Extends<GeneratedRunMutationResult, RunMutationResult>>,
  Assert<Extends<GeneratedRunStartRequest, RunStartRequest>>,
  Assert<Extends<GeneratedRunStartResult, RunStartResult>>,
  Assert<Extends<GeneratedRunStatusRequest, RunStatusRequest>>,
  Assert<Extends<GeneratedRunStatusView, RunStatusView>>,
  Assert<Extends<GeneratedRunStopRequest, RunStopRequest>>,
  Assert<Extends<GeneratedRunView, RunView>>,
];

// Keep these aliases evaluated by the compiler even though this test has no runtime assertions.
export type InstallationDtoWebToGenerated = WebToGenerated;
export type InstallationDtoGeneratedToWeb = GeneratedToWeb;
