import type {
  AcquisitionRecord as GeneratedAcquisitionRecord,
  ActiveBindingRecord as GeneratedActiveBindingRecord,
  BindingCandidate as GeneratedBindingCandidate,
  BindingCandidatesRequest as GeneratedBindingCandidatesRequest,
  BindingCandidatesResult as GeneratedBindingCandidatesResult,
  BindingListRequest as GeneratedBindingListRequest,
  BindingLifecyclePayloadSchema as GeneratedBindingLifecyclePayloadSchema,
  BindingMutationResult as GeneratedBindingMutationResult,
  BindingRevokeRequest as GeneratedBindingRevokeRequest,
  BindingSelectRequest as GeneratedBindingSelectRequest,
  BindingView as GeneratedBindingView,
  ExposureCreateRequest as GeneratedExposureCreateRequest,
  ExposureListRequest as GeneratedExposureListRequest,
  ExposureLifecyclePayloadSchema as GeneratedExposureLifecyclePayloadSchema,
  ExposureMutationResult as GeneratedExposureMutationResult,
  ExposureRevokeRequest as GeneratedExposureRevokeRequest,
  ExposureView as GeneratedExposureView,
  HostBindingListResult as GeneratedHostBindingListResult,
  HostExposureListResult as GeneratedHostExposureListResult,
  InstallationCreateRequest as GeneratedInstallationCreateRequest,
  InstallationDiff as GeneratedInstallationDiff,
  InstallationMutationResult as GeneratedInstallationMutationResult,
  InstallationRecord as GeneratedInstallationRecord,
  InstallationRemoveRequest as GeneratedInstallationRemoveRequest,
  InstallationRollbackPointer as GeneratedInstallationRollbackPointer,
  InstallationSecretPolicy as GeneratedInstallationSecretPolicy,
  InstallationStateAction as GeneratedInstallationStateAction,
  InstallationStateArtifactGetResponse as GeneratedInstallationStateArtifactGetResponse,
  InstallationUpdateRequest as GeneratedInstallationUpdateRequest,
  InstallationView as GeneratedInstallationView,
  InstallationWorkSummary as GeneratedInstallationWorkSummary,
  RightsDeclaration as GeneratedRightsDeclaration,
  TransparencyDeclaration as GeneratedTransparencyDeclaration,
  StateAction as GeneratedStateAction,
  StateBindingRecord as GeneratedStateBindingRecord,
  WorkId as GeneratedWorkId,
  HostRunListResult as GeneratedHostRunListResult,
  RunGetRequest as GeneratedRunGetRequest,
  RunListRequest as GeneratedRunListRequest,
  RunMutationResult as GeneratedRunMutationResult,
  RunStartRequest as GeneratedRunStartRequest,
  RunStartResult as GeneratedRunStartResult,
  RunStatusRequest as GeneratedRunStatusRequest,
  RunStatusView as GeneratedRunStatusView,
  RunStopRequest as GeneratedRunStopRequest,
  RunView as GeneratedRunView,
} from "../../../../sdk/typescript/contract-sdk/src/types";
import type {
  AcquisitionRecord,
  ActiveBindingRecord,
  BindingCandidate,
  BindingCandidatesRequest,
  BindingCandidatesResult,
  BindingListRequest,
  BindingLifecyclePayloadSchema,
  BindingMutationResult,
  BindingRevokeRequest,
  BindingSelectRequest,
  BindingView,
  ExposureCreateRequest,
  ExposureListRequest,
  ExposureLifecyclePayloadSchema,
  ExposureMutationResult,
  ExposureRevokeRequest,
  ExposureView,
  HostBindingListResult,
  HostExposureListResult,
  InstallationCreateRequest,
  InstallationDiff,
  InstallationMutationResult,
  InstallationRecord,
  InstallationRemoveRequest,
  InstallationRollbackPointer,
  InstallationSecretPolicy,
  InstallationStateAction,
  InstallationStateArtifactGetResponse,
  InstallationUpdateRequest,
  InstallationView,
  InstallationWorkSummary,
  RightsDeclaration,
  TransparencyDeclaration,
  StateAction,
  StateBindingRecord,
  WorkId,
  HostRunListResult,
  RunGetRequest,
  RunListRequest,
  RunMutationResult,
  RunStartRequest,
  RunStartResult,
  RunStatusRequest,
  RunStatusView,
  RunStopRequest,
  RunView,
} from "./client";

type Assert<T extends true> = T;
type Extends<From, To> = [From] extends [To] ? true : false;

type WebToGenerated = [
  Assert<Extends<AcquisitionRecord, GeneratedAcquisitionRecord>>,
  Assert<Extends<ActiveBindingRecord, GeneratedActiveBindingRecord>>,
  Assert<Extends<BindingCandidate, GeneratedBindingCandidate>>,
  Assert<Extends<BindingCandidatesRequest, GeneratedBindingCandidatesRequest>>,
  Assert<Extends<BindingCandidatesResult, GeneratedBindingCandidatesResult>>,
  Assert<Extends<BindingListRequest, GeneratedBindingListRequest>>,
  Assert<Extends<BindingLifecyclePayloadSchema, GeneratedBindingLifecyclePayloadSchema>>,
  Assert<Extends<BindingMutationResult, GeneratedBindingMutationResult>>,
  Assert<Extends<BindingRevokeRequest, GeneratedBindingRevokeRequest>>,
  Assert<Extends<BindingSelectRequest, GeneratedBindingSelectRequest>>,
  Assert<Extends<BindingView, GeneratedBindingView>>,
  Assert<Extends<ExposureCreateRequest, GeneratedExposureCreateRequest>>,
  Assert<Extends<ExposureListRequest, GeneratedExposureListRequest>>,
  Assert<Extends<ExposureLifecyclePayloadSchema, GeneratedExposureLifecyclePayloadSchema>>,
  Assert<Extends<ExposureMutationResult, GeneratedExposureMutationResult>>,
  Assert<Extends<ExposureRevokeRequest, GeneratedExposureRevokeRequest>>,
  Assert<Extends<ExposureView, GeneratedExposureView>>,
  Assert<Extends<HostBindingListResult, GeneratedHostBindingListResult>>,
  Assert<Extends<HostExposureListResult, GeneratedHostExposureListResult>>,
  Assert<Extends<InstallationCreateRequest, GeneratedInstallationCreateRequest>>,
  Assert<Extends<InstallationDiff, GeneratedInstallationDiff>>,
  Assert<Extends<InstallationMutationResult, GeneratedInstallationMutationResult>>,
  Assert<Extends<InstallationRecord, GeneratedInstallationRecord>>,
  Assert<Extends<InstallationRemoveRequest, GeneratedInstallationRemoveRequest>>,
  Assert<Extends<InstallationRollbackPointer, GeneratedInstallationRollbackPointer>>,
  Assert<Extends<InstallationSecretPolicy, GeneratedInstallationSecretPolicy>>,
  Assert<Extends<InstallationStateAction, GeneratedInstallationStateAction>>,
  Assert<Extends<InstallationStateArtifactGetResponse, GeneratedInstallationStateArtifactGetResponse>>,
  Assert<Extends<InstallationUpdateRequest, GeneratedInstallationUpdateRequest>>,
  Assert<Extends<InstallationView, GeneratedInstallationView>>,
  Assert<Extends<InstallationWorkSummary, GeneratedInstallationWorkSummary>>,
  Assert<Extends<RightsDeclaration, GeneratedRightsDeclaration>>,
  Assert<Extends<TransparencyDeclaration, GeneratedTransparencyDeclaration>>,
  Assert<Extends<StateAction, GeneratedStateAction>>,
  Assert<Extends<StateBindingRecord, GeneratedStateBindingRecord>>,
  Assert<Extends<WorkId, GeneratedWorkId>>,
  Assert<Extends<HostRunListResult, GeneratedHostRunListResult>>,
  Assert<Extends<RunGetRequest, GeneratedRunGetRequest>>,
  Assert<Extends<RunListRequest, GeneratedRunListRequest>>,
  Assert<Extends<RunMutationResult, GeneratedRunMutationResult>>,
  Assert<Extends<RunStartRequest, GeneratedRunStartRequest>>,
  Assert<Extends<RunStartResult, GeneratedRunStartResult>>,
  Assert<Extends<RunStatusRequest, GeneratedRunStatusRequest>>,
  Assert<Extends<RunStatusView, GeneratedRunStatusView>>,
  Assert<Extends<RunStopRequest, GeneratedRunStopRequest>>,
  Assert<Extends<RunView, GeneratedRunView>>,
];

type GeneratedToWeb = [
  Assert<Extends<GeneratedAcquisitionRecord, AcquisitionRecord>>,
  Assert<Extends<GeneratedActiveBindingRecord, ActiveBindingRecord>>,
  Assert<Extends<GeneratedBindingCandidate, BindingCandidate>>,
  Assert<Extends<GeneratedBindingCandidatesRequest, BindingCandidatesRequest>>,
  Assert<Extends<GeneratedBindingCandidatesResult, BindingCandidatesResult>>,
  Assert<Extends<GeneratedBindingListRequest, BindingListRequest>>,
  Assert<Extends<GeneratedBindingLifecyclePayloadSchema, BindingLifecyclePayloadSchema>>,
  Assert<Extends<GeneratedBindingMutationResult, BindingMutationResult>>,
  Assert<Extends<GeneratedBindingRevokeRequest, BindingRevokeRequest>>,
  Assert<Extends<GeneratedBindingSelectRequest, BindingSelectRequest>>,
  Assert<Extends<GeneratedBindingView, BindingView>>,
  Assert<Extends<GeneratedExposureCreateRequest, ExposureCreateRequest>>,
  Assert<Extends<GeneratedExposureListRequest, ExposureListRequest>>,
  Assert<Extends<GeneratedExposureLifecyclePayloadSchema, ExposureLifecyclePayloadSchema>>,
  Assert<Extends<GeneratedExposureMutationResult, ExposureMutationResult>>,
  Assert<Extends<GeneratedExposureRevokeRequest, ExposureRevokeRequest>>,
  Assert<Extends<GeneratedExposureView, ExposureView>>,
  Assert<Extends<GeneratedHostBindingListResult, HostBindingListResult>>,
  Assert<Extends<GeneratedHostExposureListResult, HostExposureListResult>>,
  Assert<Extends<GeneratedInstallationCreateRequest, InstallationCreateRequest>>,
  Assert<Extends<GeneratedInstallationDiff, InstallationDiff>>,
  Assert<Extends<GeneratedInstallationMutationResult, InstallationMutationResult>>,
  Assert<Extends<GeneratedInstallationRecord, InstallationRecord>>,
  Assert<Extends<GeneratedInstallationRemoveRequest, InstallationRemoveRequest>>,
  Assert<Extends<GeneratedInstallationRollbackPointer, InstallationRollbackPointer>>,
  Assert<Extends<GeneratedInstallationSecretPolicy, InstallationSecretPolicy>>,
  Assert<Extends<GeneratedInstallationStateAction, InstallationStateAction>>,
  Assert<Extends<GeneratedInstallationStateArtifactGetResponse, InstallationStateArtifactGetResponse>>,
  Assert<Extends<GeneratedInstallationUpdateRequest, InstallationUpdateRequest>>,
  Assert<Extends<GeneratedInstallationView, InstallationView>>,
  Assert<Extends<GeneratedInstallationWorkSummary, InstallationWorkSummary>>,
  Assert<Extends<GeneratedRightsDeclaration, RightsDeclaration>>,
  Assert<Extends<GeneratedTransparencyDeclaration, TransparencyDeclaration>>,
  Assert<Extends<GeneratedStateAction, StateAction>>,
  Assert<Extends<GeneratedStateBindingRecord, StateBindingRecord>>,
  Assert<Extends<GeneratedWorkId, WorkId>>,
  Assert<Extends<GeneratedHostRunListResult, HostRunListResult>>,
  Assert<Extends<GeneratedRunGetRequest, RunGetRequest>>,
  Assert<Extends<GeneratedRunListRequest, RunListRequest>>,
  Assert<Extends<GeneratedRunMutationResult, RunMutationResult>>,
  Assert<Extends<GeneratedRunStartRequest, RunStartRequest>>,
  Assert<Extends<GeneratedRunStartResult, RunStartResult>>,
  Assert<Extends<GeneratedRunStatusRequest, RunStatusRequest>>,
  Assert<Extends<GeneratedRunStatusView, RunStatusView>>,
  Assert<Extends<GeneratedRunStopRequest, RunStopRequest>>,
  Assert<Extends<GeneratedRunView, RunView>>,
];

// Keep these aliases evaluated by the compiler even though this test has no runtime assertions.
export type InstallationDtoWebToGenerated = WebToGenerated;
export type InstallationDtoGeneratedToWeb = GeneratedToWeb;

type HasAuthorityHandle<T> = "authority_handle_id" extends keyof T ? true : false;
type AssertFalse<T extends false> = T;
export type PublicBindingCandidateHasNoAuthorityHandle = AssertFalse<HasAuthorityHandle<BindingCandidate>>;
export type PublicBindingViewHasNoAuthorityHandle = AssertFalse<HasAuthorityHandle<BindingView>>;
export type PublicBindingRecordHasNoAuthorityHandle = AssertFalse<HasAuthorityHandle<BindingView["record"]>>;
export type PublicActiveBindingRecordHasNoAuthorityHandle = AssertFalse<HasAuthorityHandle<ActiveBindingRecord>>;
export type BackupIsGeneratedInstallationStateAction = Assert<
  Extends<{ kind: "backup" }, InstallationStateAction>
>;
