// @generated by cargo run -p plurora-cli --bin generate-sdks
// TypeScript event payloads generated from docs/spec/v1/schemas/events/.
import type { AssetRecord, AuthorityDeniedPayload, BindingLifecyclePayloadSchema, BranchRecord, CapabilityFailedPayload, CapabilityInvocationResult, CapabilityInvokedPayload, CapabilityStreamStartedPayload, ContextClosedPayload, ContextOpenedPayload, DeploymentHealthEventPayload, DeploymentReconcileSummary, ErrorShape, ExposureLifecyclePayloadSchema, HostExecCompletedPayload, HostExecDeniedPayload, HostExecFailedPayload, HostExecRequestPayload, HostExecStartedPayload, HostExecStoppedPayload, HostOutboundExecuteCompletedPayload, HostOutboundWebsocketCompletedPayload, HostOutboundWebsocketErrorPayload, HostOutboundWebsocketFramePayload, HostOutboundWebsocketOpenedPayload, HostPortDeniedPayload, HostPortLeasedPayload, HostPortReleasedPayload, HostProxyDeniedPayload, HostProxyRegisteredPayload, HostProxyUnregisteredPayload, InstallationCreatedPayloadSchema, InstallationRemovedPayloadSchema, InstallationUpdatedPayloadSchema, OutboundAuditRecord, OutboundAuditRecord2, OutboundStreamSummary, PackageLifecyclePayload, PermissionGrantRecord, ProjectionDefinition, ProposalRecord, RunLifecyclePayloadSchema, StreamFrameEnvelope, StreamFrameEnvelope2, SubprocessLogLine } from "./types";

export interface AuthorityDeniedEvent {
  kind: "authority/denied";
  payload: AuthorityDeniedPayload;
}

export interface AuthorityGrantCreatedEvent {
  kind: "authority/grant.created";
  payload: PermissionGrantRecord;
}

export interface AuthorityGrantRevokedEvent {
  kind: "authority/grant.revoked";
  payload: PermissionGrantRecord;
}

export interface CapabilityCompletedEvent {
  kind: "capability/completed";
  payload: CapabilityInvocationResult;
}

export interface CapabilityFailedEvent {
  kind: "capability/failed";
  payload: CapabilityFailedPayload;
}

export interface CapabilityInvokedEvent {
  kind: "capability/invoked";
  payload: CapabilityInvokedPayload;
}

export interface CapabilityStreamCancelledEvent {
  kind: "capability/stream.cancelled";
  payload: StreamFrameEnvelope2;
}

export interface CapabilityStreamChunkEvent {
  kind: "capability/stream.chunk";
  payload: StreamFrameEnvelope;
}

export interface CapabilityStreamEndedEvent {
  kind: "capability/stream.ended";
  payload: StreamFrameEnvelope2;
}

export interface CapabilityStreamErrorEvent {
  kind: "capability/stream.error";
  payload: StreamFrameEnvelope2;
}

export interface CapabilityStreamProgressEvent {
  kind: "capability/stream.progress";
  payload: StreamFrameEnvelope;
}

export interface CapabilityStreamStartedEvent {
  kind: "capability/stream.started";
  payload: CapabilityStreamStartedPayload;
}

export interface CapabilityStreamTimeoutEvent {
  kind: "capability/stream.timeout";
  payload: StreamFrameEnvelope2;
}

export interface ChangeProposalAppliedEvent {
  kind: "change/proposal.applied";
  payload: ProposalRecord;
}

export interface ChangeProposalApprovedEvent {
  kind: "change/proposal.approved";
  payload: ProposalRecord;
}

export interface ChangeProposalCreatedEvent {
  kind: "change/proposal.created";
  payload: ProposalRecord;
}

export interface ChangeProposalFailedEvent {
  kind: "change/proposal.failed";
  payload: ProposalRecord;
}

export interface ChangeProposalRejectedEvent {
  kind: "change/proposal.rejected";
  payload: ProposalRecord;
}

export interface ContextClosedEvent {
  kind: "context/closed";
  payload: ContextClosedPayload;
}

export interface ContextForkedEvent {
  kind: "context/forked";
  payload: BranchRecord;
}

export interface ContextOpenedEvent {
  kind: "context/opened";
  payload: ContextOpenedPayload;
}

export interface HostBindingExpiredEvent {
  kind: "host/binding.expired";
  payload: BindingLifecyclePayloadSchema;
}

export interface HostBindingRevokedEvent {
  kind: "host/binding.revoked";
  payload: BindingLifecyclePayloadSchema;
}

export interface HostBindingSelectedEvent {
  kind: "host/binding.selected";
  payload: BindingLifecyclePayloadSchema;
}

export interface HostDeploymentHealthEvent {
  kind: "host/deployment.health";
  payload: DeploymentHealthEventPayload;
}

export interface HostDeploymentReconciledEvent {
  kind: "host/deployment.reconciled";
  payload: DeploymentReconcileSummary;
}

export interface HostExecCompletedEvent {
  kind: "host/exec.completed";
  payload: HostExecCompletedPayload;
}

export interface HostExecDeniedEvent {
  kind: "host/exec.denied";
  payload: HostExecDeniedPayload;
}

export interface HostExecFailedEvent {
  kind: "host/exec.failed";
  payload: HostExecFailedPayload;
}

export interface HostExecRequestEvent {
  kind: "host/exec.request";
  payload: HostExecRequestPayload;
}

export interface HostExecStartedEvent {
  kind: "host/exec.started";
  payload: HostExecStartedPayload;
}

export interface HostExecStoppedEvent {
  kind: "host/exec.stopped";
  payload: HostExecStoppedPayload;
}

export interface HostExposureCreatedEvent {
  kind: "host/exposure.created";
  payload: ExposureLifecyclePayloadSchema;
}

export interface HostExposureExpiredEvent {
  kind: "host/exposure.expired";
  payload: ExposureLifecyclePayloadSchema;
}

export interface HostExposureRevokedEvent {
  kind: "host/exposure.revoked";
  payload: ExposureLifecyclePayloadSchema;
}

export interface HostInstallationCreatedEvent {
  kind: "host/installation.created";
  payload: InstallationCreatedPayloadSchema;
}

export interface HostInstallationRemovedEvent {
  kind: "host/installation.removed";
  payload: InstallationRemovedPayloadSchema;
}

export interface HostInstallationUpdatedEvent {
  kind: "host/installation.updated";
  payload: InstallationUpdatedPayloadSchema;
}

export interface HostOutboundDeniedEvent {
  kind: "host/outbound.denied";
  payload: OutboundAuditRecord;
}

export interface HostOutboundExecuteCompletedEvent {
  kind: "host/outbound.execute.completed";
  payload: HostOutboundExecuteCompletedPayload;
}

export interface HostOutboundRequestEvent {
  kind: "host/outbound.request";
  payload: OutboundAuditRecord2;
}

export interface HostOutboundStreamCompletedEvent {
  kind: "host/outbound.stream.completed";
  payload: OutboundStreamSummary;
}

export interface HostOutboundWebsocketCompletedEvent {
  kind: "host/outbound.websocket.completed";
  payload: HostOutboundWebsocketCompletedPayload;
}

export interface HostOutboundWebsocketErrorEvent {
  kind: "host/outbound.websocket.error";
  payload: HostOutboundWebsocketErrorPayload;
}

export interface HostOutboundWebsocketFrameEvent {
  kind: "host/outbound.websocket.frame";
  payload: HostOutboundWebsocketFramePayload;
}

export interface HostOutboundWebsocketOpenedEvent {
  kind: "host/outbound.websocket.opened";
  payload: HostOutboundWebsocketOpenedPayload;
}

export interface HostPackageDegradedEvent {
  kind: "host/package.degraded";
  payload: PackageLifecyclePayload;
}

export interface HostPackageLoadedEvent {
  kind: "host/package.loaded";
  payload: PackageLifecyclePayload;
}

export interface HostPackageLoadingEvent {
  kind: "host/package.loading";
  payload: PackageLifecyclePayload;
}

export interface HostPackageLogEvent {
  kind: "host/package.log";
  payload: SubprocessLogLine;
}

export interface HostPackageReadyEvent {
  kind: "host/package.ready";
  payload: PackageLifecyclePayload;
}

export interface HostPackageStartingEvent {
  kind: "host/package.starting";
  payload: PackageLifecyclePayload;
}

export interface HostPackageStoppedEvent {
  kind: "host/package.stopped";
  payload: PackageLifecyclePayload;
}

export interface HostPackageStoppingEvent {
  kind: "host/package.stopping";
  payload: PackageLifecyclePayload;
}

export interface HostPackageUnloadedEvent {
  kind: "host/package.unloaded";
  payload: PackageLifecyclePayload;
}

export interface HostPortDeniedEvent {
  kind: "host/port.denied";
  payload: HostPortDeniedPayload;
}

export interface HostPortLeasedEvent {
  kind: "host/port.leased";
  payload: HostPortLeasedPayload;
}

export interface HostPortReleasedEvent {
  kind: "host/port.released";
  payload: HostPortReleasedPayload;
}

export interface HostProxyDeniedEvent {
  kind: "host/proxy.denied";
  payload: HostProxyDeniedPayload;
}

export interface HostProxyRegisteredEvent {
  kind: "host/proxy.registered";
  payload: HostProxyRegisteredPayload;
}

export interface HostProxyUnregisteredEvent {
  kind: "host/proxy.unregistered";
  payload: HostProxyUnregisteredPayload;
}

export interface HostRunFailedEvent {
  kind: "host/run.failed";
  payload: RunLifecyclePayloadSchema;
}

export interface HostRunStartedEvent {
  kind: "host/run.started";
  payload: RunLifecyclePayloadSchema;
}

export interface HostRunStartingEvent {
  kind: "host/run.starting";
  payload: RunLifecyclePayloadSchema;
}

export interface HostRunStoppedEvent {
  kind: "host/run.stopped";
  payload: RunLifecyclePayloadSchema;
}

export interface HostRunStoppingEvent {
  kind: "host/run.stopping";
  payload: RunLifecyclePayloadSchema;
}

export interface ObjectPutEvent {
  kind: "object/put";
  payload: AssetRecord;
}

export interface ProjectionUpdatedEvent {
  kind: "projection/updated";
  payload: ProjectionDefinition;
}

export interface RuntimeErrorEvent {
  kind: "runtime/error";
  payload: ErrorShape;
}

export interface PlatformEventPayloadMap {
  "authority/denied": AuthorityDeniedPayload;
  "authority/grant.created": PermissionGrantRecord;
  "authority/grant.revoked": PermissionGrantRecord;
  "capability/completed": CapabilityInvocationResult;
  "capability/failed": CapabilityFailedPayload;
  "capability/invoked": CapabilityInvokedPayload;
  "capability/stream.cancelled": StreamFrameEnvelope2;
  "capability/stream.chunk": StreamFrameEnvelope;
  "capability/stream.ended": StreamFrameEnvelope2;
  "capability/stream.error": StreamFrameEnvelope2;
  "capability/stream.progress": StreamFrameEnvelope;
  "capability/stream.started": CapabilityStreamStartedPayload;
  "capability/stream.timeout": StreamFrameEnvelope2;
  "change/proposal.applied": ProposalRecord;
  "change/proposal.approved": ProposalRecord;
  "change/proposal.created": ProposalRecord;
  "change/proposal.failed": ProposalRecord;
  "change/proposal.rejected": ProposalRecord;
  "context/closed": ContextClosedPayload;
  "context/forked": BranchRecord;
  "context/opened": ContextOpenedPayload;
  "host/binding.expired": BindingLifecyclePayloadSchema;
  "host/binding.revoked": BindingLifecyclePayloadSchema;
  "host/binding.selected": BindingLifecyclePayloadSchema;
  "host/deployment.health": DeploymentHealthEventPayload;
  "host/deployment.reconciled": DeploymentReconcileSummary;
  "host/exec.completed": HostExecCompletedPayload;
  "host/exec.denied": HostExecDeniedPayload;
  "host/exec.failed": HostExecFailedPayload;
  "host/exec.request": HostExecRequestPayload;
  "host/exec.started": HostExecStartedPayload;
  "host/exec.stopped": HostExecStoppedPayload;
  "host/exposure.created": ExposureLifecyclePayloadSchema;
  "host/exposure.expired": ExposureLifecyclePayloadSchema;
  "host/exposure.revoked": ExposureLifecyclePayloadSchema;
  "host/installation.created": InstallationCreatedPayloadSchema;
  "host/installation.removed": InstallationRemovedPayloadSchema;
  "host/installation.updated": InstallationUpdatedPayloadSchema;
  "host/outbound.denied": OutboundAuditRecord;
  "host/outbound.execute.completed": HostOutboundExecuteCompletedPayload;
  "host/outbound.request": OutboundAuditRecord2;
  "host/outbound.stream.completed": OutboundStreamSummary;
  "host/outbound.websocket.completed": HostOutboundWebsocketCompletedPayload;
  "host/outbound.websocket.error": HostOutboundWebsocketErrorPayload;
  "host/outbound.websocket.frame": HostOutboundWebsocketFramePayload;
  "host/outbound.websocket.opened": HostOutboundWebsocketOpenedPayload;
  "host/package.degraded": PackageLifecyclePayload;
  "host/package.loaded": PackageLifecyclePayload;
  "host/package.loading": PackageLifecyclePayload;
  "host/package.log": SubprocessLogLine;
  "host/package.ready": PackageLifecyclePayload;
  "host/package.starting": PackageLifecyclePayload;
  "host/package.stopped": PackageLifecyclePayload;
  "host/package.stopping": PackageLifecyclePayload;
  "host/package.unloaded": PackageLifecyclePayload;
  "host/port.denied": HostPortDeniedPayload;
  "host/port.leased": HostPortLeasedPayload;
  "host/port.released": HostPortReleasedPayload;
  "host/proxy.denied": HostProxyDeniedPayload;
  "host/proxy.registered": HostProxyRegisteredPayload;
  "host/proxy.unregistered": HostProxyUnregisteredPayload;
  "host/run.failed": RunLifecyclePayloadSchema;
  "host/run.started": RunLifecyclePayloadSchema;
  "host/run.starting": RunLifecyclePayloadSchema;
  "host/run.stopped": RunLifecyclePayloadSchema;
  "host/run.stopping": RunLifecyclePayloadSchema;
  "object/put": AssetRecord;
  "projection/updated": ProjectionDefinition;
  "runtime/error": ErrorShape;
}

export type PlatformEvent =
  | AuthorityDeniedEvent
  | AuthorityGrantCreatedEvent
  | AuthorityGrantRevokedEvent
  | CapabilityCompletedEvent
  | CapabilityFailedEvent
  | CapabilityInvokedEvent
  | CapabilityStreamCancelledEvent
  | CapabilityStreamChunkEvent
  | CapabilityStreamEndedEvent
  | CapabilityStreamErrorEvent
  | CapabilityStreamProgressEvent
  | CapabilityStreamStartedEvent
  | CapabilityStreamTimeoutEvent
  | ChangeProposalAppliedEvent
  | ChangeProposalApprovedEvent
  | ChangeProposalCreatedEvent
  | ChangeProposalFailedEvent
  | ChangeProposalRejectedEvent
  | ContextClosedEvent
  | ContextForkedEvent
  | ContextOpenedEvent
  | HostBindingExpiredEvent
  | HostBindingRevokedEvent
  | HostBindingSelectedEvent
  | HostDeploymentHealthEvent
  | HostDeploymentReconciledEvent
  | HostExecCompletedEvent
  | HostExecDeniedEvent
  | HostExecFailedEvent
  | HostExecRequestEvent
  | HostExecStartedEvent
  | HostExecStoppedEvent
  | HostExposureCreatedEvent
  | HostExposureExpiredEvent
  | HostExposureRevokedEvent
  | HostInstallationCreatedEvent
  | HostInstallationRemovedEvent
  | HostInstallationUpdatedEvent
  | HostOutboundDeniedEvent
  | HostOutboundExecuteCompletedEvent
  | HostOutboundRequestEvent
  | HostOutboundStreamCompletedEvent
  | HostOutboundWebsocketCompletedEvent
  | HostOutboundWebsocketErrorEvent
  | HostOutboundWebsocketFrameEvent
  | HostOutboundWebsocketOpenedEvent
  | HostPackageDegradedEvent
  | HostPackageLoadedEvent
  | HostPackageLoadingEvent
  | HostPackageLogEvent
  | HostPackageReadyEvent
  | HostPackageStartingEvent
  | HostPackageStoppedEvent
  | HostPackageStoppingEvent
  | HostPackageUnloadedEvent
  | HostPortDeniedEvent
  | HostPortLeasedEvent
  | HostPortReleasedEvent
  | HostProxyDeniedEvent
  | HostProxyRegisteredEvent
  | HostProxyUnregisteredEvent
  | HostRunFailedEvent
  | HostRunStartedEvent
  | HostRunStartingEvent
  | HostRunStoppedEvent
  | HostRunStoppingEvent
  | ObjectPutEvent
  | ProjectionUpdatedEvent
  | RuntimeErrorEvent
;
