// @generated by cargo run -p plurora-cli --bin generate-sdks
// TypeScript types generated from docs/spec/v1/schemas/.

export type AccessMode = "read_only" | "read_write" | "append_only";

export type AcquisitionKind = "work_bundle" | "package" | "git_snapshot" | "local_import" | "remote_catalog" | "foreign_binding";

export interface AcquisitionRecord {
  "kind": AcquisitionKind;
  "provenance_refs"?: Array<ArtifactDescriptor>;
  "source_ref"?: ArtifactDescriptor | null;
  "update_channel"?: null | string;
}

export interface ActiveBindingRecord {
  "binding_id": BindingId;
  "consumer_installation_id": InstallationId;
  "consumer_port": PortId;
  "expires_at"?: null | string;
  "exposure_id": ExposureId;
  "transport": SelectedTransport;
}

export interface AppendEventRequest {
  "kind": string;
  "metadata": unknown;
  "payload": unknown;
  "session_id": string;
  "writer_package_id": string;
}

export interface ArtifactDescriptor {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
}

export interface AssemblyBinding {
  "annotations"?: Record<string, unknown>;
  "binding_id": string;
  "consumer": PortEndpoint;
  "phase": BindingPhase;
  "provider": PortEndpoint;
  "transport_policy"?: TransportPolicy;
}

export type AssemblyId = string;

export interface AssemblyLock {
  "assembly": ArtifactDescriptor;
  "bindings"?: Array<BindingLock>;
  "content_roots"?: Array<ArtifactDescriptor>;
  "nodes": Array<NodeLock>;
  "protocol_profiles"?: Array<ProtocolProfilePin>;
  "schema": "plurora.assembly-lock.v1";
}

export interface AssemblyNode {
  "annotations"?: Record<string, unknown>;
  "configuration"?: ArtifactDescriptor | null;
  "node_id": NodeId;
  "ports"?: Array<PortDescriptor>;
  "source": AssemblyNodeSource;
}

export type AssemblyNodeSource = {
  "assembly": ArtifactDescriptor;
  "kind": "assembly";
} | {
  "component": ArtifactDescriptor;
  "kind": "component";
};

export interface AssemblyPortExposure {
  "annotations"?: Record<string, unknown>;
  "direction": PortDirection;
  "port_id": PortId;
  "target": PortEndpoint;
}

export interface AssemblyRevision {
  "annotations"?: Record<string, unknown>;
  "assembly_id": AssemblyId;
  "bindings"?: Array<AssemblyBinding>;
  "exposed_ports"?: Array<AssemblyPortExposure>;
  "nodes": Array<AssemblyNode>;
  "schema": "plurora.assembly-revision.v1";
  "state_slots"?: Array<StateSlotDescriptor>;
}

/**
 * Encoding used by the public `object.put` and `object.get` content field.
 */
export type AssetContentEncoding = "utf8" | "hex";

/**
 * Original ordinary-Asset selector for `object.get`.
 */
export interface AssetGetParams {
  "asset_id": string;
}

/**
 * Original ordinary-Asset result for `object.get`.
 */
export interface AssetGetResponse {
  "content": string;
  "record": AssetRecord;
}

export interface AssetPermissions {
  "read"?: boolean;
  "write"?: boolean;
}

export interface AssetPutRequest {
  "artifact"?: ExactArtifactUpload | null;
  "content": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id"?: null | string;
}

export interface AssetRecord {
  "created_at": string;
  "descriptor"?: ArtifactDescriptor | null;
  "hash": string;
  "id": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id": string;
  "size_bytes": number;
}

export interface AuditPackageParams {
  "package_id": string;
  "since"?: null | string;
  "until"?: null | string;
}

export type AuthorityDecisionListResult = Array<{
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}>;

export interface AuthorityDeniedPayload {
  "operation"?: string;
  "package_id"?: string;
}

export type AuthorityGrantListResult = Array<{
  "granted_at": string;
  "id": string;
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "revoked_at"?: null | string;
  "scope"?: null | string;
}>;

export type AuthorityHandleRevokeResult = Record<string, unknown>;

export type AvailabilityPolicy = "required" | "degraded_without" | "optional";

export type BackupPolicy = "required" | "allowed" | "forbidden";

export interface BindingCandidate {
  "availability": AvailabilityPolicy;
  /**
   * Digest of every canonical field below, including verified descriptive disclosure. Selection uses this digest, never an order-sensitive digest of the whole candidate set. Sorting ignores descriptive and publisher fields, but any disclosure drift still makes a prior decision stale.
   */
  "candidate_digest": string;
  "capability": CapabilityPin;
  "consumer": BindingEndpointPin;
  "consumer_port": PortDescriptor;
  "effective_expires_at"?: null | string;
  "exposure": ExposureView;
  "phase": BindingPhase;
  "provider": BindingEndpointPin;
  "provider_component": BindingComponentDisclosure;
  "provider_installation": BindingInstallationDisclosure;
  "provider_port": PortDescriptor;
  "provider_work": BindingWorkDisclosure;
  "transport": SelectedTransport;
}

export interface BindingCandidatesRequest {
  "consumer_installation_id": InstallationId;
  "consumer_run"?: RunRevisionPin | null;
  "expected_consumer_installation_revision": number;
  "import_port": PortId;
  "phase": BindingPhase;
  /**
   * An ordering hint only. It never selects a candidate or grants authority.
   */
  "preferences"?: Array<ResourceSelector>;
}

export interface BindingCandidatesResult {
  "candidates": Array<BindingCandidate>;
  "gaps"?: Array<BindingGap>;
}

/**
 * Host-verified Component identity and evidence. This is deliberately narrower than ComponentDescriptor so annotations, surfaces, and content roots cannot become an accidental disclosure channel.
 */
export interface BindingComponentDisclosure {
  "behavior": ArtifactDescriptor;
  "claim_status": ComponentClaimStatus;
  "component_artifact": ArtifactDescriptor;
  "component_id": string;
  "enforced_boundaries": ComponentBoundaryClaims;
  "entry_kind": string;
  "package_id": string;
  "protocol_implementations"?: Array<PackagedProtocolDescriptor>;
  "trust_class": ComponentTrustClass;
  "version": string;
}

export type BindingDecisionStatus = "selected" | "revoked" | "expired";

export type BindingEffectiveStatus = {
  "kind": "active";
} | {
  "kind": "broken";
  "reason_code": string;
} | {
  "kind": "detached";
};

export interface BindingEndpointPin {
  "component": ComponentPin;
  "installation": InstallationRevisionPin;
  "port": ResolvedPortPin;
  "run"?: RunRevisionPin | null;
}

export interface BindingGap {
  "installation_id"?: InstallationId | null;
  "interaction_model"?: null | string;
  "next_step": string;
  "node_id"?: NodeId | null;
  "port_id"?: PortId | null;
  "reason_code": string;
  "run_id"?: RunId | null;
}

export type BindingId = string;

/**
 * Verified, public Installation origin shown before a Binding decision. It intentionally excludes state bindings, secret policy, and host-local paths.
 */
export interface BindingInstallationDisclosure {
  "display_name": string;
  "installation_id": InstallationId;
  "installation_revision": number;
  "source": AcquisitionRecord;
}

export interface BindingLifecyclePayloadSchema {
  "binding": BindingView;
}

export interface BindingListRequest {
  "consumer_installation_id"?: InstallationId | null;
  "run_id"?: RunId | null;
  "status"?: BindingDecisionStatus | null;
}

export interface BindingLock {
  "binding_id": string;
  "consumer": PortEndpoint;
  "phase": BindingPhase;
  "provider": PortEndpoint;
  "provider_component": ArtifactDescriptor;
  "transport": SelectedTransport;
}

export interface BindingMutationResult {
  "affected_binding_ids"?: Array<BindingId>;
  "binding": BindingView;
  "idempotent": boolean;
}

export type BindingPhase = "authoring" | "installation" | "launch" | "runtime";

export interface BindingRevokeRequest {
  "binding_id": BindingId;
  "consumer_installation_id": InstallationId;
  "consumer_run"?: RunRevisionPin | null;
  "expected_binding_revision": number;
  "expected_consumer_installation_revision": number;
  "exposure_id": ExposureId;
  "idempotency_key": string;
  "import_port": PortId;
}

export interface BindingSelectRequest {
  "candidate_digest": string;
  "consumer_installation_id": InstallationId;
  "consumer_run"?: RunRevisionPin | null;
  "expected_consumer_installation_revision": number;
  "expected_exposure_revision": number;
  "expected_provider_installation_revision": number;
  "exposure_id": ExposureId;
  "idempotency_key": string;
  "import_port": PortId;
  "phase": BindingPhase;
  "provider_installation_id": InstallationId;
}

export interface BindingSelectionRecord {
  "availability": AvailabilityPolicy;
  "binding_id": BindingId;
  "candidate_digest": string;
  "capability": CapabilityPin;
  "consumer": BindingEndpointPin;
  "effective_expires_at"?: null | string;
  "exposure_id": ExposureId;
  "exposure_revision": number;
  "phase": BindingPhase;
  "provider": BindingEndpointPin;
  "status": BindingDecisionStatus;
  "transport": SelectedTransport;
}

export interface BindingView {
  "effective_status": BindingEffectiveStatus;
  "record": BindingSelectionRecord;
  "revision": number;
}

/**
 * Verified, public Work identity shown before a Binding decision. Descriptive text is disclosure, never preference or execution authority.
 */
export interface BindingWorkDisclosure {
  "title": string;
  "work_id": WorkId;
}

export interface BranchRecord {
  "child_session_id": string;
  "created_at": string;
  "forked_from_sequence": number;
  "id": string;
  "metadata"?: unknown;
  "parent_session_id": string;
}

export interface BuildAction {
  "action_id": string;
  "builder_id": string;
  "input_refs"?: Array<ArtifactDescriptor>;
  "node_id": NodeId;
  "output_id": string;
  "parameter_ref": ArtifactDescriptor;
}

export interface CapAttenuateParams {
  "constraints": unknown;
  "parent_handle": CapHandleId;
}

export interface CapHandle {
  "cap_type": string;
  "cap_version": string;
  "constraints": unknown;
  "id": CapHandleId;
  "lease": HandleLease;
  "parent"?: CapHandleId | null;
  "provenance": HandleProvenance;
  "revoked": boolean;
  "scope": HandleScope;
}

export type CapHandleId = string;

export interface CapHandleResult {
  "handle": CapHandle;
}

export interface CapHandlesResult {
  "handles": Array<CapHandle>;
}

export interface CapListForParams {
  "package_id": string;
}

export interface CapRevokeParams {
  "handle": CapHandleId;
}

export interface CapabilityCancelParams {
  "invocation_id"?: null | string;
  "session_id"?: null | string;
  "stream_id"?: null | string;
}

export type CapabilityDescribeResult = null;

export interface CapabilityDescriptor {
  "description"?: null | string;
  "id": string;
  "input_schema"?: unknown;
  "output_schema"?: unknown;
  "side_effects"?: Array<string>;
  "streaming"?: boolean;
  "version": string;
}

export type CapabilityDiscoverResult = Array<{
  "descriptor": CapabilityDescriptor;
  "provider_behavior_digest"?: string;
  "provider_claim_status"?: ComponentClaimStatus;
  "provider_component_digest"?: string;
  "provider_component_id"?: string;
  "provider_enforced_boundaries"?: ComponentBoundaryClaims;
  "provider_package_id": string;
  "provider_trust_class"?: ComponentTrustClass;
}>;

export interface CapabilityFailedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export interface CapabilityInvocationRequest {
  "caller_package_id"?: null | string;
  /**
   * Legacy path. Runtime auto-mints a one-use transient handle when no handle is supplied.
   */
  "capability_id"?: null | string;
  /**
   * New preferred path: invoke by kernel-minted handle.
   */
  "handle"?: CapHandleId | null;
  "input"?: unknown;
  "provider_package_id"?: null | string;
  /**
   * Kernel session id this invocation is part of, if any. Propagated from ProtocolContext for downstream scope resolution.
   */
  "session_id"?: null | string;
  "version"?: null | string;
}

export interface CapabilityInvocationResult {
  "capability_id": string;
  "correlation_id": string;
  "duration_ms": number;
  "output": unknown;
  "provider_behavior_digest"?: string;
  "provider_component_digest"?: string;
  "provider_component_id"?: string;
  "provider_package_id": string;
  "provider_trust_class"?: ComponentTrustClass;
  "receipt"?: ArtifactDescriptor | null;
  "replay_mode"?: EffectReplayMode | null;
}

export type CapabilityInvokedPayload = Record<string, unknown>;

export interface CapabilityPermissions {
  "invoke"?: Array<string>;
}

export interface CapabilityPin {
  "capability_id": string;
  "capability_version": string;
}

export interface CapabilityRequirement {
  "id": string;
  "version": string;
}

export interface CapabilityStreamParams {
  "capability_id": string;
  "input": unknown;
  "provider_package_id"?: null | string;
}

export type CapabilityStreamResult = Record<string, unknown>;

export type CapabilityStreamStartedPayload = Record<string, unknown>;

export interface ChangeCommit {
  "branch_id"?: null | string;
  "change_set_id": string;
  "commit_type_uri"?: string;
  "completed_at": string;
  "error"?: null | string;
  "id": string;
  "idempotency_key"?: null | string;
  "operation_receipts"?: Array<ArtifactDescriptor>;
  "result_refs"?: Array<ArtifactDescriptor>;
  "started_at": string;
  "status": ChangeCommitStatus;
}

export type ChangeCommitStatus = "committed" | "failed" | "partial";

export interface ChangeOperation {
  "input_refs"?: Array<ArtifactDescriptor>;
  "op": string;
  "payload"?: unknown;
  "target"?: null | string;
}

export interface ChangePrecondition {
  "expected"?: unknown;
  "kind": string;
  "target"?: null | string;
}

export type ChangeProposalListResult = Array<{
  "approval"?: ProposalApproval | null;
  "change_set"?: ChangeSet | null;
  "commit"?: ChangeCommit | null;
  "created_at"?: string;
  "created_by"?: ProtocolPrincipal;
  "expected_effects"?: unknown;
  "id"?: string;
  "intent"?: Intent | null;
  "operations"?: Array<ProposalOperation>;
  "policy_decision"?: PolicyDecision | null;
  "receipt"?: ArtifactDescriptor | null;
  "required_permissions"?: Array<string>;
  "result"?: unknown;
  "status"?: ProposalStatus;
  "target_branch_id"?: null | string;
  "target_session_id"?: null | string;
}>;

export interface ChangeSet {
  "change_set_type_uri"?: string;
  "created_at": string;
  "expected_effects"?: unknown;
  "id": string;
  "idempotency_key"?: null | string;
  "intent_id": string;
  "operations"?: Array<ChangeOperation>;
  "preconditions"?: Array<ChangePrecondition>;
  "required_authority"?: Array<string>;
}

export type ClaimStatus = "claimed" | "verified" | "refuted" | "unknown";

export interface ComponentBoundaryClaims {
  "filesystem_isolation": boolean;
  "network_isolation": boolean;
  "no_code_execution": boolean;
  "process_failure_isolation": boolean;
  "remote_identity": boolean;
  "resource_limits_enforced": boolean;
  "revocation_enforced": boolean;
  "tenancy_isolation": boolean;
}

export type ComponentClaimStatus = "declared" | "legacy_adapted" | "foreign_capsule";

export interface ComponentDeclaration {
  "annotations"?: Record<string, unknown>;
  "capability_ids"?: Array<string>;
  "content_roots"?: Array<ArtifactDescriptor>;
  "id": string;
  "protocol_implementations"?: Array<ProtocolImplementationDeclaration>;
  "surface_ids"?: Array<string>;
  "version": string;
}

export interface ComponentDescriptor {
  "annotations"?: Record<string, unknown>;
  "artifact": ArtifactDescriptor;
  "behavior": ArtifactDescriptor;
  "capability_ids": Array<string>;
  "claim_status": ComponentClaimStatus;
  "component_id": string;
  "content_roots"?: Array<ArtifactDescriptor>;
  "enforced_boundaries": ComponentBoundaryClaims;
  "entry_kind": string;
  "protocol_implementations"?: Array<PackagedProtocolDescriptor>;
  "surfaces"?: Array<PackagedSurfaceDescriptor>;
  "trust_class": ComponentTrustClass;
  "version": string;
}

export interface ComponentPin {
  "behavior_digest": string;
  "component_artifact": ArtifactDescriptor;
  "component_id": string;
  "node_path": Array<NodeId>;
  "package_id": string;
  "trust_class": ComponentTrustClass;
}

export type ComponentTrustClass = "sandboxed_component" | "isolated_process" | "remote_boundary" | "trusted_native" | "static_resource" | "foreign_capsule";

export type ContextBranchListResult = Array<{
  "child_session_id": string;
  "created_at": string;
  "forked_from_sequence": number;
  "id": string;
  "metadata"?: unknown;
  "parent_session_id": string;
}>;

export type ContextClosedPayload = Record<string, unknown>;

export type ContextListResult = null;

export type ContextOpenedPayload = Record<string, unknown>;

export interface ContractLayerInfo {
  "description": string;
  "id": ContractOwnerLayer;
  "maturity": ContractMaturity;
}

export type ContractMaturity = "experimental" | "candidate" | "stable";

export interface ContractMethod {
  "id": string;
  "implementation_status": MethodStatus;
  "introduced_in": string;
  "maturity": ContractMaturity;
  "owner_layer": ContractOwnerLayer;
  "request_schema": string;
  "response_schema": string;
  "streaming": boolean;
}

export type ContractMode = "none" | "v1";

export type ContractOwnerLayer = "substrate" | "host" | "protocol" | "shell";

export interface ContractProfileInfo {
  "id": string;
  "maturity": ContractMaturity;
  "versions": Array<ContractVersionRequirement>;
}

export interface ContractSelection {
  "profile": string;
  "protocols"?: Array<ProtocolSelection>;
  "versions"?: Array<ContractVersionRequirement>;
}

export interface ContractVersionInfo {
  "layer": ContractOwnerLayer;
  "maturity": ContractMaturity;
  "version": string;
}

export interface ContractVersionRequirement {
  "layer": ContractOwnerLayer;
  "version": string;
}

export interface DeclaredAuthority {
  "assets_read": boolean;
  "assets_write": boolean;
  "capabilities_invoke": Array<string>;
  "events_append": boolean;
  "events_read": boolean;
  "network_hosts": Array<string>;
  "secret_refs": Array<string>;
}

export type DependencySource = {
  "kind": "git";
  /**
   * Tag, branch, or commit ref
   */
  "ref"?: string;
  "url": string;
} | {
  "kind": "internal";
} | {
  "kind": "local";
  "path": string;
};

export interface DeploymentHealthEventPayload {
  "failure_count": number;
  "port_lease_id"?: null | string;
  "previous_ready": boolean;
  "probe": DeploymentHealthProbe;
  "ready": boolean;
  "reason": string;
  "route_id": string;
}

export interface DeploymentHealthProbe {
  "kind": string;
}

export interface DeploymentReconcileSummary {
  "execs_failed": number;
  "leases_promoted": number;
  "leases_released": number;
  "routes_promoted": number;
  "routes_removed": number;
}

export type EffectClass = "pure" | "deterministic_stateful" | "recorded_nondeterministic" | "external_effecting" | "realtime_best_effort";

export interface EffectReceipt {
  "actual"?: unknown;
  "annotations"?: Record<string, unknown>;
  "approval_ref"?: ArtifactDescriptor | null;
  "authority_ref"?: ArtifactDescriptor | null;
  "completed_at": string;
  "component_ref": ArtifactDescriptor;
  "cost"?: unknown;
  "effect_kind": string;
  "external_effect_refs"?: Array<ArtifactDescriptor>;
  "input_refs"?: Array<ArtifactDescriptor>;
  "latency_ms": number;
  "output_refs"?: Array<ArtifactDescriptor>;
  "parent_receipts"?: Array<string>;
  "planned"?: unknown;
  "policy_decision_ref"?: ArtifactDescriptor | null;
  "principal": PrincipalIdentity;
  "protocol_profiles"?: Array<string>;
  "receipt_id": string;
  "receipt_type_uri": string;
  "replay_mode": EffectReplayMode;
  "schema_version": number;
  "scope"?: EffectScope;
  "started_at": string;
  "status": EffectTerminalStatus;
  "trace_id": string;
  "usage"?: unknown;
}

export type EffectReplayMode = "live" | "historical" | "reexecute";

export interface EffectScope {
  "branch_id"?: null | string;
  "session_id"?: null | string;
}

export type EffectTerminalStatus = "succeeded" | "denied" | "failed" | "cancelled" | "timed_out" | "partial";

export type EmptyParams = Record<string, unknown>;

export interface EndpointAction {
  "action_id": string;
  "endpoint_id": string;
  "target_id": string;
  "transport": SelectedTransport;
  "visibility": EndpointVisibility;
}

export interface EndpointIntent {
  "annotations"?: Record<string, unknown>;
  "endpoint_id": string;
  "port": PortEndpoint;
  "protocol_hint"?: null | string;
  "visibility": EndpointVisibility;
}

export type EndpointVisibility = "private" | "shared" | "public";

export type EntryDescriptor = {
  "abi_version": number;
  "crate_ref": string;
  "kind": "rust_inproc";
  "symbol": string;
} | {
  "abi_version": number;
  "kind": "wasm";
  "memory_limit_mb": number;
  "module": string;
} | {
  "auth": RemoteAuth;
  "endpoint": string;
  "kind": "remote";
} | {
  "bundle": string;
  "kind": "surface_bundle";
} | {
  "command": Array<string>;
  "kind": "subprocess";
  "transport"?: SubprocessTransport;
};

export interface ErrorShape {
  "code": string;
  "details": unknown;
  "message": string;
}

export interface EventEnvelope {
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}

export interface EventListRequest {
  "after_sequence"?: null | number;
  "kind_prefix"?: null | string;
  "limit"?: null | number;
  "session_id": string;
  "writer_package_id"?: null | string;
}

export interface EventPermissions {
  "append"?: boolean;
  "read"?: boolean;
}

/**
 * Explicit request contract for transporting an exact portable artifact.
 */
export interface ExactArtifactUpload {
  "content_encoding": AssetContentEncoding;
  "descriptor": ArtifactDescriptor;
  "scope": ObjectPutScope;
}

export interface ExecCommand {
  "args"?: Array<string>;
  "program": string;
}

export interface ExecIdParams {
  "exec_id": string;
}

export type ExecLifecyclePolicy = "stop_on_session_close" | "keep_alive" | "stop_on_idle";

export interface ExecResourceLimits {
  "max_cpu_millis"?: null | number;
  "max_duration_ms"?: null | number;
  "max_log_bytes"?: null | number;
  "max_memory_mb"?: null | number;
}

export interface ExecStatus {
  "exec_id"?: null | string;
  "exit_code"?: null | number;
  "kind": ExecStatusKind;
  "message"?: null | string;
  "ready": boolean;
  "target_id"?: null | string;
}

export type ExecStatusKind = "pending" | "running" | "stopped" | "exited" | "failed" | "denied" | "unknown";

export interface ExecutionTarget {
  /**
   * Effective capabilities after protocol negotiation and Host policy.
   */
  "capabilities"?: Array<ExecutionTargetCapability>;
  /**
   * Capabilities declared by the target before Host policy is applied.
   */
  "declared_capabilities"?: Array<ExecutionTargetCapability>;
  "enrolled_at_ms"?: null | number;
  "heartbeat_expires_at_ms"?: null | number;
  "id": string;
  "identity_ref"?: null | string;
  "labels"?: Record<string, string>;
  "last_seen_at_ms"?: null | number;
  "lease_epoch"?: number;
  "name": string;
  "observed"?: ExecutionTargetObservedSummary | null;
  "policy_epoch"?: number;
  "protocol_versions"?: Array<string>;
  "reachability": ExecutionTargetReachability;
  "revoked_at_ms"?: null | number;
  "selected_protocol_version"?: null | string;
  "status": ExecutionTargetStatusKind;
}

export type ExecutionTargetCapability = "local_exec" | "port_lease" | "http_proxy_upstream" | "websocket_proxy_upstream" | "artifact_transfer" | "declarative_verifier" | "health_probe" | "deployment" | "authenticated_tunnel";

export interface ExecutionTargetObservedSummary {
  "artifact_count"?: number;
  "running_operation_count"?: number;
  "workload_count"?: number;
}

export type ExecutionTargetReachability = "local_host" | "direct" | "reverse_tunnel";

export type ExecutionTargetStatusKind = "enrolling" | "available" | "degraded" | "offline" | "draining" | "incompatible" | "revoked" | "unavailable";

/**
 * The kind of outbound executor that produced a response.
 */
export type ExecutorKind = "deny_all" | "fake" | "real";

export interface ExposureCreateRequest {
  "audience": Array<ResourceSelector>;
  "expected_installation_revision": number;
  "expected_run_revision": number;
  "expires_at"?: null | string;
  "export_port": PortId;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "run_id": RunId;
}

export type ExposureId = string;

export interface ExposureLifecyclePayloadSchema {
  "exposure": ExposureView;
}

export interface ExposureListRequest {
  "installation_id"?: InstallationId | null;
  "run_id"?: RunId | null;
  "status"?: ExposureStatus | null;
}

export interface ExposureMutationResult {
  "affected_binding_ids"?: Array<BindingId>;
  "exposure": ExposureView;
  "idempotent": boolean;
}

export interface ExposureRecord {
  "audience": Array<ResourceSelector>;
  "expires_at"?: null | string;
  "export_port": PortId;
  "exposure_id": ExposureId;
  "installation_id": InstallationId;
  "run_id"?: RunId | null;
  "status": ExposureStatus;
}

export interface ExposureRevokeRequest {
  "expected_exposure_revision": number;
  "expected_installation_revision": number;
  "expected_run_revision": number;
  "export_port": PortId;
  "exposure_id": ExposureId;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "run_id": RunId;
}

export type ExposureStatus = "active" | "expired" | "revoked";

export interface ExposureView {
  "record": ExposureRecord;
  "revision": number;
}

export interface ExtensionPointDescriptor {
  "id": string;
  "modifiable": boolean;
  "payload_schema"?: unknown;
  "short_circuit": boolean;
  "timing": HookTiming;
  "version": string;
}

export interface FilesystemImport {
  "access": AccessMode;
  "import_id": string;
  "resource_id": string;
}

export interface FilesystemPermissions {
  "read"?: Array<string>;
  "write"?: Array<string>;
}

export type FrameKind = "text" | "binary";

export interface HandleLease {
  "expires_at"?: null | string;
  "invocations_used": number;
  "max_invocations"?: null | number;
}

export interface HandleProvenance {
  "granted_at": string;
  /**
   * "plurora/runtime" if minted by the platform runtime.
   */
  "granted_by_package_id": string;
  /**
   * e.g. "auto_mint", "package_load", "attenuate", "delegate".
   */
  "via_method": string;
}

export interface HandleScope {
  "holder_package_id": string;
  "session_id"?: null | string;
}

export type HealthStatus = "unknown" | "healthy" | "degraded" | "unhealthy";

export interface HookSubscription {
  "extension_point": string;
  "handler": string;
  "precedence"?: number;
  "timing": HookTiming;
}

export type HookTiming = "sync" | "async";

export type HostBindingListResult = Array<{
  "effective_status": BindingEffectiveStatus;
  "record": BindingSelectionRecord;
  "revision": number;
}>;

export type HostDiagnosticsResult = Record<string, unknown>;

export interface HostExecCompletedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export interface HostExecDeniedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export interface HostExecFailedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export type HostExecRequestPayload = Record<string, unknown>;

export type HostExecStartedPayload = Record<string, unknown>;

export interface HostExecStoppedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export type HostExposureListResult = Array<{
  "record": ExposureRecord;
  "revision": number;
}>;

export interface HostInfo {
  "contract_methods"?: Array<ContractMethod> | null;
  "contract_registry_version"?: null | string;
  "default_profile"?: null | string;
  "layers"?: Array<ContractLayerInfo> | null;
  "maturity"?: ContractMaturity | null;
  "methods": Array<ProtocolMethod>;
  "profiles"?: Array<ContractProfileInfo> | null;
  "protocol_commons_registry_version"?: null | string;
  "protocol_version": string;
  "protocols"?: Array<ProtocolDescriptor> | null;
  "supported_transports": Array<string>;
  "versions"?: Array<ContractVersionInfo> | null;
}

export type HostInstallationListResult = Array<{
  "record": InstallationRecord;
  "revision": number;
  "rollback"?: InstallationRollbackPointer | null;
  "work_summary": InstallationWorkSummary;
}>;

export type HostOutboundAuditResult = Array<{
  /**
   * Capability through which the request was made.
   */
  "capability_id": string;
  /**
   * Cost placeholder.
   */
  "cost"?: unknown;
  /**
   * Destination host.
   */
  "destination_host": string;
  /**
   * Error message if status is not "allowed".
   */
  "error"?: null | string;
  /**
   * Unique record id.
   */
  "id": string;
  /**
   * HTTP method (GET, POST, etc).
   */
  "method": string;
  /**
   * Package that owns the outbound request.
   */
  "package_id": string;
  /**
   * The principal that initiated the request.
   */
  "principal": string;
  /**
   * Declared purpose from the manifest or request context.
   */
  "purpose"?: null | string;
  /**
   * Redaction state — what data, if any, was recorded.
   */
  "redaction_state"?: RedactionState;
  /**
   * Secret references used (not raw secrets).
   */
  "secret_refs_used"?: Array<string>;
  /**
   * Request status: "allowed", "denied", "error", etc.
   */
  "status": string;
  /**
   * Usage placeholder (e.g. token count).
   */
  "usage"?: unknown;
}>;

export interface HostOutboundExecuteCompletedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export type HostOutboundWebsocketCloseResult = Record<string, unknown>;

export interface HostOutboundWebsocketCompletedPayload {
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
}

export type HostOutboundWebsocketErrorPayload = Record<string, unknown>;

export type HostOutboundWebsocketFramePayload = Record<string, unknown>;

export type HostOutboundWebsocketOpenResult = Record<string, unknown>;

export type HostOutboundWebsocketOpenedPayload = Record<string, unknown>;

export type HostOutboundWebsocketSendResult = Record<string, unknown>;

export type HostPackageDescribeResult = null;

export type HostPackageListResult = Array<{
  "capability_count": number;
  "components"?: Array<ComponentDescriptor>;
  "enforced_boundaries"?: ComponentBoundaryClaims;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "id": string;
  "last_failure"?: PackageFailureSummary | null;
  "loaded_at": string;
  "manifest": PackageManifest;
  "package_envelope"?: PackageEnvelopeDescriptor | null;
  "state": PackageState;
  /**
   * Canonical Contract v2 trust classification. Unlike `trust_level`, this distinguishes `contract:none` as a foreign capsule.
   */
  "trust_class"?: ComponentTrustClass;
  "trust_level": TrustLevel;
  "updated_at": string;
  "version": string;
}>;

export type HostPackageLogsResult = Array<{
  "line": string;
  "package_id": string;
  "stream": string;
}>;

export interface HostPingResult {
  "ok": true;
}

export type HostPortDeniedPayload = Record<string, unknown>;

export type HostPortLeasedPayload = Record<string, unknown>;

export type HostPortListResult = Array<{
  "bind": PortBindScope;
  "host": string;
  "id": string;
  "port": number;
  "port_name": string;
  "protocol": PortProtocol;
  "status": PortLeaseStatusKind;
  "target_id": string;
}>;

export type HostPortReleasedPayload = Record<string, unknown>;

export type HostProxyDeniedPayload = Record<string, unknown>;

export type HostProxyListResult = Array<{
  "access"?: ProxyRouteAccess;
  "id": string;
  "iframe_url": string;
  "protocol": ProxyProtocol;
  "public_url": string;
  "ready": boolean;
  "status": ProxyRouteStatusKind;
  "upstream": ProxyRouteUpstream;
}>;

export type HostProxyRegisteredPayload = Record<string, unknown>;

export type HostProxyUnregisteredPayload = Record<string, unknown>;

export type HostRealizationListResult = Array<{
  "activated_at"?: null | string;
  "actual_resources"?: Array<RealizedResource>;
  "created_at": string;
  "health": RealizationHealth;
  "installation_id": InstallationId;
  "parent_realization_id"?: RealizationId | null;
  "plan_ref": ArtifactDescriptor;
  "realization_id": RealizationId;
  "receipts"?: Array<ArtifactDescriptor>;
  "revision": number;
  "status": RealizationStatus;
  "stopped_at"?: null | string;
  "updated_at": string;
}>;

export type HostRunListResult = Array<{
  "entrypoint_id": string;
  "installation_revision": number;
  "record": RunRecord;
  "revision": number;
}>;

export type HostTargetListResult = Array<{
  /**
   * Effective capabilities after protocol negotiation and Host policy.
   */
  "capabilities"?: Array<ExecutionTargetCapability>;
  /**
   * Capabilities declared by the target before Host policy is applied.
   */
  "declared_capabilities"?: Array<ExecutionTargetCapability>;
  "enrolled_at_ms"?: null | number;
  "heartbeat_expires_at_ms"?: null | number;
  "id": string;
  "identity_ref"?: null | string;
  "labels"?: Record<string, string>;
  "last_seen_at_ms"?: null | number;
  "lease_epoch"?: number;
  "name": string;
  "observed"?: ExecutionTargetObservedSummary | null;
  "policy_epoch"?: number;
  "protocol_versions"?: Array<string>;
  "reachability": ExecutionTargetReachability;
  "revoked_at_ms"?: null | number;
  "selected_protocol_version"?: null | string;
  "status": ExecutionTargetStatusKind;
}>;

export type IdentityCurrentResult = null;

export type InstallationChangeForArtifactDescriptor = {
  "after": ArtifactDescriptor;
  "before": ArtifactDescriptor;
  "kind": "changed";
} | {
  "after": ArtifactDescriptor;
  "kind": "added";
} | {
  "before": ArtifactDescriptor;
  "kind": "removed";
};

export type InstallationChangeForAssemblyBinding = {
  "after": AssemblyBinding;
  "before": AssemblyBinding;
  "kind": "changed";
} | {
  "after": AssemblyBinding;
  "kind": "added";
} | {
  "before": AssemblyBinding;
  "kind": "removed";
};

export type InstallationChangeForAssemblyNode = {
  "after": AssemblyNode;
  "before": AssemblyNode;
  "kind": "changed";
} | {
  "after": AssemblyNode;
  "kind": "added";
} | {
  "before": AssemblyNode;
  "kind": "removed";
};

export type InstallationChangeForAssemblyPortExposure = {
  "after": AssemblyPortExposure;
  "before": AssemblyPortExposure;
  "kind": "changed";
} | {
  "after": AssemblyPortExposure;
  "kind": "added";
} | {
  "before": AssemblyPortExposure;
  "kind": "removed";
};

export type InstallationChangeForBindingLock = {
  "after": BindingLock;
  "before": BindingLock;
  "kind": "changed";
} | {
  "after": BindingLock;
  "kind": "added";
} | {
  "before": BindingLock;
  "kind": "removed";
};

export type InstallationChangeForNodeLock = {
  "after": NodeLock;
  "before": NodeLock;
  "kind": "changed";
} | {
  "after": NodeLock;
  "kind": "added";
} | {
  "before": NodeLock;
  "kind": "removed";
};

export type InstallationChangeForProtocolProfilePin = {
  "after": ProtocolProfilePin;
  "before": ProtocolProfilePin;
  "kind": "changed";
} | {
  "after": ProtocolProfilePin;
  "kind": "added";
} | {
  "before": ProtocolProfilePin;
  "kind": "removed";
};

export type InstallationChangeForWorkEntrypoint = {
  "after": WorkEntrypoint;
  "before": WorkEntrypoint;
  "kind": "changed";
} | {
  "after": WorkEntrypoint;
  "kind": "added";
} | {
  "before": WorkEntrypoint;
  "kind": "removed";
};

export interface InstallationCreateRequest {
  "assembly_lock": ArtifactDescriptor;
  "display_name": string;
  "idempotency_key": string;
  "secret_policy"?: InstallationSecretPolicy;
  "source": AcquisitionRecord;
  "state_bindings"?: Array<StateBindingRecord>;
  "work_id": WorkId;
  "work_revision": ArtifactDescriptor;
}

export interface InstallationCreatedPayloadSchema {
  "claim": InstallationIdempotencyClaimSchema;
  "view": InstallationView;
}

export interface InstallationDiff {
  "assembly_bindings"?: Array<InstallationItemDiffForAssemblyBinding>;
  "assembly_exposed_ports"?: Array<InstallationItemDiffForAssemblyPortExposure>;
  "assembly_lock_bindings"?: Array<InstallationItemDiffForBindingLock>;
  "assembly_lock_changed": boolean;
  "assembly_lock_content_roots"?: Array<InstallationItemDiffForArtifactDescriptor>;
  "assembly_lock_nodes"?: Array<InstallationItemDiffForNodeLock>;
  "assembly_lock_protocol_profiles"?: Array<InstallationItemDiffForProtocolProfilePin>;
  "assembly_nodes"?: Array<InstallationItemDiffForAssemblyNode>;
  "display_name_changed": boolean;
  "secret_policy_changed": boolean;
  "source_changed": boolean;
  "state_bindings_changed": boolean;
  "state_slots"?: Array<InstallationStateSlotDiff>;
  "work_content_roots"?: Array<InstallationItemDiffForArtifactDescriptor>;
  "work_entrypoints"?: Array<InstallationItemDiffForWorkEntrypoint>;
  "work_operational_intent"?: InstallationChangeForArtifactDescriptor | null;
  "work_revision_changed": boolean;
  "work_rights"?: InstallationChangeForArtifactDescriptor | null;
  "work_transparency"?: InstallationChangeForArtifactDescriptor | null;
}

export interface InstallationGetRequest {
  "installation_id": InstallationId;
}

export type InstallationId = string;

export interface InstallationIdempotencyClaimSchema {
  /**
   * SHA-256 of the canonical mutation request fingerprint.
   */
  "fingerprint": string;
  /**
   * SHA-256 of the caller-supplied key. The raw idempotency key is never journaled.
   */
  "key_hash": string;
  "result": InstallationMutationResult;
}

export interface InstallationItemDiffForArtifactDescriptor {
  "change": InstallationChangeForArtifactDescriptor;
  "id": string;
}

export interface InstallationItemDiffForAssemblyBinding {
  "change": InstallationChangeForAssemblyBinding;
  "id": string;
}

export interface InstallationItemDiffForAssemblyNode {
  "change": InstallationChangeForAssemblyNode;
  "id": string;
}

export interface InstallationItemDiffForAssemblyPortExposure {
  "change": InstallationChangeForAssemblyPortExposure;
  "id": string;
}

export interface InstallationItemDiffForBindingLock {
  "change": InstallationChangeForBindingLock;
  "id": string;
}

export interface InstallationItemDiffForNodeLock {
  "change": InstallationChangeForNodeLock;
  "id": string;
}

export interface InstallationItemDiffForProtocolProfilePin {
  "change": InstallationChangeForProtocolProfilePin;
  "id": string;
}

export interface InstallationItemDiffForWorkEntrypoint {
  "change": InstallationChangeForWorkEntrypoint;
  "id": string;
}

export interface InstallationListRequest {
  "status"?: InstallationStatus | null;
}

export interface InstallationMutationResult {
  "diff"?: InstallationDiff | null;
  "idempotent": boolean;
  "installation": InstallationView;
  "receipts"?: Array<ArtifactDescriptor>;
}

export interface InstallationRecord {
  "assembly_lock": ArtifactDescriptor;
  "created_at": string;
  "display_name": string;
  "installation_id": InstallationId;
  "schema_version": 1;
  "secret_policy"?: InstallationSecretPolicy;
  "source": AcquisitionRecord;
  "state_bindings"?: Array<StateBindingRecord>;
  "status": InstallationStatus;
  "updated_at": string;
  "work_revision": ArtifactDescriptor;
}

export interface InstallationRemoveRequest {
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "state_disposition": StateDisposition;
}

export interface InstallationRemovedPayloadSchema {
  "claim": InstallationIdempotencyClaimSchema;
  /**
   * Internal UUID for state deletion; null when state is explicitly retained.
   */
  "operation_id": null | string;
  "previous_revision": number;
  "view": InstallationView;
}

export interface InstallationRevisionPin {
  "assembly_lock": ArtifactDescriptor;
  "installation_id": InstallationId;
  "installation_revision": number;
  "work_revision": ArtifactDescriptor;
}

export interface InstallationRollbackPointer {
  "assembly_lock": ArtifactDescriptor;
  "revision": number;
  "state_snapshot"?: ArtifactDescriptor | null;
  "work_revision": ArtifactDescriptor;
}

export interface InstallationSecretPolicy {
  "allow_platform_fallback"?: boolean;
  "allowed_secret_refs"?: Array<string>;
}

export type InstallationStateAction = {
  "kind": "preserve";
} | {
  "kind": "replace";
  "replacement_snapshot": ArtifactDescriptor;
} | {
  "kind": "reset";
};

/**
 * Audit-only selector for a journal-issued Installation state artifact.
 */
export interface InstallationStateArtifactGetParams {
  "installation_state_artifact": ArtifactDescriptor;
}

/**
 * Audit-only result for a journal-issued Installation state artifact.
 */
export interface InstallationStateArtifactGetResponse {
  "content": string;
  "content_encoding": AssetContentEncoding;
  "descriptor": ArtifactDescriptor;
}

export interface InstallationStateAuthorityEvidence {
  "action": string;
  "expires_at_ms"?: null | number;
  "grant_id"?: null | string;
  "installation_id": InstallationId;
  "schema": string;
}

export type InstallationStateDecision = "allow" | "deny";

export type InstallationStateDecisionAction = "reset" | "replace";

export interface InstallationStateDecisionReceipt {
  "action": InstallationStateDecisionAction;
  "authority_evidence": Array<ArtifactDescriptor>;
  "candidate_lock_digest": string;
  "candidate_work_digest": string;
  "decision": InstallationStateDecision;
  "expected_revision": number;
  "installation_id": InstallationId;
  "operation": string;
  "replacement_snapshot_digest"?: null | string;
  "schema": string;
}

export type InstallationStateSlotChange = {
  "after": StateSlotDescriptor;
  "before": StateSlotDescriptor;
  "kind": "changed";
} | {
  "after": StateSlotDescriptor;
  "kind": "added";
} | {
  "before": StateSlotDescriptor;
  "kind": "removed";
};

export interface InstallationStateSlotDiff {
  "change": InstallationStateSlotChange;
  /**
   * Structural action required when the Installation state tree is non-empty. An empty state tree still reports the difference without forcing an effect.
   */
  "required_action"?: InstallationStateSlotRequirement;
  "state_slot_id": StateSlotId;
}

export type InstallationStateSlotRequirement = "none" | "replace" | "reset";

export interface InstallationStateSnapshot {
  "entries": Array<InstallationStateSnapshotEntry>;
  "schema": string;
}

export interface InstallationStateSnapshotEntry {
  "bytes": Array<number>;
  "path": string;
}

export type InstallationStatus = "resolving" | "ready" | "updating" | "blocked" | "failed" | "removing" | "removed";

export interface InstallationUpdateRequest {
  "assembly_lock": ArtifactDescriptor;
  "display_name"?: null | string;
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "secret_policy"?: InstallationSecretPolicy | null;
  "source"?: AcquisitionRecord | null;
  "state_action": InstallationStateAction;
  "state_bindings"?: Array<StateBindingRecord> | null;
  "work_revision": ArtifactDescriptor;
}

export interface InstallationUpdatedPayloadSchema {
  "claim": InstallationIdempotencyClaimSchema;
  /**
   * Internal UUID for a state-changing operation; null for pointer-only updates.
   */
  "operation_id": null | string;
  "previous_revision": number;
  "view": InstallationView;
}

export interface InstallationView {
  "record": InstallationRecord;
  "revision": number;
  "rollback"?: InstallationRollbackPointer | null;
  "work_summary": InstallationWorkSummary;
}

/**
 * Host-projected discovery metadata from the exact, verified WorkRevision selected by an Installation. This is descriptive content, not authority.
 */
export interface InstallationWorkSummary {
  "annotations": Record<string, unknown>;
  "content_roots": Array<ArtifactDescriptor>;
  "description": string;
  "entrypoints": Array<WorkEntrypoint>;
  "operational_intent"?: ArtifactDescriptor | null;
  "rights"?: ArtifactDescriptor | null;
  "title": string;
  "transparency"?: ArtifactDescriptor | null;
  "work_id": WorkId;
}

export interface Intent {
  "annotations"?: Record<string, unknown>;
  "created_at": string;
  "goal"?: unknown;
  "id": string;
  "intent_type_uri"?: string;
  "principal": PrincipalIdentity;
  "target_branch_id"?: null | string;
  "target_session_id"?: null | string;
}

export type JournalListResult = Array<{
  "id": string;
  "kind": string;
  "metadata"?: unknown;
  "payload": unknown;
  "schema_version": number;
  "sequence": number;
  "session_id": string;
  "timestamp": string;
  "writer_package_id": string;
}>;

export type JournalSubscribeResult = null;

export interface LaunchAction {
  "action_id": string;
  "artifact": ArtifactDescriptor;
  "node_id": NodeId;
  "parameter_ref"?: ArtifactDescriptor | null;
  "target_id": string;
}

export interface LocalExecDeclaration {
  "max_count"?: null | number;
  "programs"?: Array<string>;
  "target_id": string;
}

export interface LocalExecListResponse {
  "executions": Array<ExecStatus>;
}

export interface LocalExecLogLine {
  "message_redacted": string;
  "seq": number;
  "stream": LocalExecLogStream;
}

export type LocalExecLogStream = "stdout" | "stderr" | "system";

export interface LocalExecLogsRequest {
  "exec_id": string;
  "limit"?: null | number;
  "since_seq"?: null | number;
}

export interface LocalExecLogsResponse {
  "error"?: null | string;
  "exec_id": string;
  "lines": Array<LocalExecLogLine>;
  "next_seq"?: null | number;
}

export interface LocalExecPermissions {
  "declarations"?: Array<LocalExecDeclaration>;
  "max_count"?: null | number;
}

export interface LocalExecStartRequest {
  "command": ExecCommand;
  /**
   * Required by the live executor. Fake/deny executors tolerate omission for backwards-compatible protocol fixtures.
   */
  "cwd"?: null | string;
  /**
   * Explicit environment to pass to the child. The live executor clears the inherited environment and forwards only keys allowed by host policy.
   */
  "env"?: Record<string, string>;
  "lifecycle"?: ExecLifecyclePolicy;
  "port_names"?: Array<string>;
  "readiness_probe"?: ReadinessProbe;
  "resource_limits"?: ExecResourceLimits;
  "target_id": string;
}

export interface LocalExecStartResponse {
  "error"?: null | string;
  "exec_id"?: null | string;
  "status": ExecStatus;
}

export interface LocalExecStatusResponse {
  "error"?: null | string;
  "status": ExecStatus;
}

export interface LocalExecStopRequest {
  "exec_id": string;
  "reason"?: null | string;
}

export interface LocalExecStopResponse {
  "error"?: null | string;
  "exec_id": string;
  "status": ExecStatus;
}

export type ManagedTargetBuildNetworkMode = "none" | "bridge";

export type MethodStatus = "implemented" | "partial" | "planned";

export interface NamedPackageArtifact {
  "descriptor": ArtifactDescriptor;
  "id": string;
}

/**
 * A single network access declaration in a package manifest.
 *
 * Each entry describes an allowed outbound destination with host, permitted HTTP methods, and a human-readable purpose. The runtime / host policy checker matches outbound requests against declared entries. Packages with no `network` declarations must not make any outbound network requests.
 */
export interface NetworkDeclaration {
  /**
   * Destination host (e.g. `"api.openai.com"` or `"*.example.org"`).
   */
  "host": string;
  /**
   * Permitted HTTP/WebSocket methods (e.g. `["GET", "POST", "WEBSOCKET"]`). Empty means all.
   */
  "methods"?: Array<string>;
  /**
   * Human-readable purpose for this network access.
   */
  "purpose"?: null | string;
}

export interface NetworkImport {
  "allowed_destinations"?: Array<string>;
  "import_id": string;
  "protocol": string;
}

export interface NetworkPermissions {
  /**
   * Structured network declarations (host, methods, purpose).
   */
  "declarations"?: Array<NetworkDeclaration>;
  /**
   * Flat host list for backward compatibility. Packages using the structured form should populate `declarations` instead.
   */
  "hosts"?: Array<string>;
}

export type NodeId = string;

export interface NodeInstanceRecord {
  "instance_id": string;
  "node_id": NodeId;
  "node_path": Array<NodeId>;
  "realization_id"?: RealizationId | null;
  "status": NodeInstanceStatus;
}

export type NodeInstanceStatus = "starting" | "running" | "degraded" | "stopping" | "stopped" | "failed" | "interrupted";

export interface NodeLock {
  "artifact": ArtifactDescriptor;
  "behavior_digest"?: null | string;
  "node_id": NodeId;
  "trust_class"?: ComponentTrustClass | null;
}

export interface NodePlacement {
  "execution_class": string;
  "node_id": NodeId;
  "placement_id": string;
  "target_id": string;
}

export type ObjectGetRequest = AssetGetParams | InstallationStateArtifactGetParams;

export type ObjectGetResponse = AssetGetResponse | InstallationStateArtifactGetResponse;

export type ObjectListResult = Array<{
  "created_at": string;
  "descriptor"?: ArtifactDescriptor | null;
  "hash": string;
  "id": string;
  "metadata"?: unknown;
  "mime": string;
  "origin_package_id": string;
  "size_bytes": number;
}>;

export interface ObjectPutResponse {
  "asset": AssetRecord | null;
  "descriptor": ArtifactDescriptor;
}

/**
 * Installation mutation which may consume an exact portable artifact upload.
 */
export type ObjectPutScope = {
  "installation_id": InstallationId;
  "kind": "installation_update";
  "work_id": WorkId;
} | {
  "kind": "installation_create";
  "work_id": WorkId;
};

export interface OpenSessionRequest {
  "active_package_set": Array<string>;
  "labels": Array<string>;
  "metadata": unknown;
}

export interface OperationalIntent {
  "annotations"?: Record<string, unknown>;
  "endpoints"?: Array<EndpointIntent>;
  "placement"?: Array<PlacementConstraint>;
  "schema": "plurora.operational-intent.v1";
  "state"?: Array<StatePlacementIntent>;
  "update_policy"?: UpdatePolicy;
  "workloads"?: Array<WorkloadIntent>;
}

export interface OutboundAuditParams {
  "package_id": string;
}

/**
 * Generic outbound audit record / envelope.
 *
 * Records an outbound network request made by a package through Plurora-provided network/request helpers. This is a platform event payload — it does NOT contain raw secrets, bodies, headers, prompts, or responses. Only `secret_ref` identifiers and the `redaction_state` are recorded.
 */
export interface OutboundAuditRecord {
  /**
   * Capability through which the request was made.
   */
  "capability_id": string;
  /**
   * Cost placeholder.
   */
  "cost"?: unknown;
  /**
   * Destination host.
   */
  "destination_host": string;
  /**
   * Error message if status is not "allowed".
   */
  "error"?: null | string;
  /**
   * Unique record id.
   */
  "id": string;
  /**
   * HTTP method (GET, POST, etc).
   */
  "method": string;
  /**
   * Package that owns the outbound request.
   */
  "package_id": string;
  /**
   * The principal that initiated the request.
   */
  "principal": string;
  /**
   * Declared purpose from the manifest or request context.
   */
  "purpose"?: null | string;
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
  /**
   * Redaction state — what data, if any, was recorded.
   */
  "redaction_state"?: RedactionState;
  /**
   * Secret references used (not raw secrets).
   */
  "secret_refs_used"?: Array<string>;
  /**
   * Request status: "allowed", "denied", "error", etc.
   */
  "status": string;
  /**
   * Usage placeholder (e.g. token count).
   */
  "usage"?: unknown;
}

/**
 * Generic outbound audit record / envelope.
 *
 * Records an outbound network request made by a package through Plurora-provided network/request helpers. This is a platform event payload — it does NOT contain raw secrets, bodies, headers, prompts, or responses. Only `secret_ref` identifiers and the `redaction_state` are recorded.
 */
export interface OutboundAuditRecord2 {
  /**
   * Capability through which the request was made.
   */
  "capability_id": string;
  /**
   * Cost placeholder.
   */
  "cost"?: unknown;
  /**
   * Destination host.
   */
  "destination_host": string;
  /**
   * Error message if status is not "allowed".
   */
  "error"?: null | string;
  /**
   * Unique record id.
   */
  "id": string;
  /**
   * HTTP method (GET, POST, etc).
   */
  "method": string;
  /**
   * Package that owns the outbound request.
   */
  "package_id": string;
  /**
   * The principal that initiated the request.
   */
  "principal": string;
  /**
   * Declared purpose from the manifest or request context.
   */
  "purpose"?: null | string;
  /**
   * Redaction state — what data, if any, was recorded.
   */
  "redaction_state"?: RedactionState;
  /**
   * Secret references used (not raw secrets).
   */
  "secret_refs_used"?: Array<string>;
  /**
   * Request status: "allowed", "denied", "error", etc.
   */
  "status": string;
  /**
   * Usage placeholder (e.g. token count).
   */
  "usage"?: unknown;
}

export interface OutboundExecuteParams {
  "body_shape": unknown;
  "capability_id": string;
  "destination_host": string;
  "metadata": unknown;
  "method": string;
  "package_id"?: null | string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Array<OutboundSecretHeaderSpec>;
  "secret_refs": Array<string>;
  "static_headers": Array<OutboundStaticHeader>;
  "timeout_ms"?: null | number;
}

/**
 * Response returned by an outbound executor.
 *
 * Like the request, this is content-free. It carries status, the *shape* of headers/body, usage/cost placeholders, and metadata identifying what kind of executor produced the response.
 */
export interface OutboundExecutorResponse {
  /**
   * JSON *shape* of the response body.
   */
  "body_shape"?: unknown;
  /**
   * Cost placeholder (e.g. `{"total_cost_usd": 0.002}`).
   */
  "cost"?: unknown;
  /**
   * What kind of executor produced this response.
   */
  "executor_kind": ExecutorKind;
  /**
   * JSON *shape* of the response headers (e.g. `{"content-type": "application/json", "x-ratelimit-remaining": "..."}`).
   */
  "headers_shape"?: unknown;
  /**
   * Whether real network I/O was performed.
   */
  "network_performed": boolean;
  /**
   * Provider-assigned request id (e.g. `req-abc123`).
   */
  "provider_request_id"?: null | string;
  /**
   * Redaction state applied to the response.
   */
  "redaction_state"?: RedactionState;
  /**
   * High-level status: "ok", "error", "denied", "timeout".
   */
  "status": string;
  /**
   * HTTP-style status code if applicable (e.g. 200, 429, 503).
   */
  "status_code"?: null | number;
  /**
   * Usage placeholder (e.g. `{"prompt_tokens": 10, "completion_tokens": 20}`).
   */
  "usage"?: unknown;
}

/**
 * Specification for a secret-derived HTTP header to be injected by the host during outbound execution. Packages declare these in `host.outbound.execute` params as `secret_headers`; the host resolves the `secret_ref` at execution time and injects the resulting header value into the live HTTP request.
 *
 * Raw secret values never appear in audit, response, or Debug output.
 */
export interface OutboundSecretHeaderSpec {
  "header_name": string;
  "scheme": string;
  "secret_ref": string;
}

/**
 * A safe non-secret static header for outbound requests (L5).
 *
 * Only header names on the `STATIC_HEADER_ALLOWLIST` are permitted. Secret-bearing header names (Authorization, x-api-key, Cookie, etc.) are rejected at parse time. Values must be plain strings that do not look like raw secrets.
 */
export interface OutboundStaticHeader {
  "name": string;
  "value": string;
}

export interface OutboundStreamParams {
  "body_shape": unknown;
  "capability_id": string;
  "destination_host": string;
  "max_duration_ms"?: null | number;
  "max_frame_bytes"?: null | number;
  "max_total_bytes"?: null | number;
  "metadata": unknown;
  "method": string;
  "package_id"?: null | string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Array<OutboundSecretHeaderSpec>;
  "secret_refs": Array<string>;
  "static_headers": Array<OutboundStaticHeader>;
  "stream_format"?: StreamFormat | null;
  "timeout_ms"?: null | number;
}

/**
 * Response returned by `host.outbound.stream` on the initial call.
 *
 * Contains the stream_id for subscribing to events, the start status, and metadata about the executor that will handle the stream.
 */
export interface OutboundStreamResponse {
  /**
   * What kind of executor is handling the stream.
   */
  "executor_kind": ExecutorKind;
  /**
   * Whether real network I/O will be performed.
   */
  "network_performed": boolean;
  /**
   * Redaction state applied to stream frames.
   */
  "redaction_state"?: RedactionState;
  /**
   * Whether the stream started successfully.
   */
  "status": StreamStartStatus;
  /**
   * The stream_id to subscribe to for stream frames.
   */
  "stream_id": string;
}

/**
 * Summary of a completed outbound stream, returned by the executor.
 */
export interface OutboundStreamSummary {
  /**
   * JSON shape of the response body (redacted preview).
   */
  "body_shape"?: unknown;
  /**
   * Total bytes received.
   */
  "bytes_received": number;
  /**
   * What kind of executor produced this summary.
   */
  "executor_kind": ExecutorKind;
  /**
   * Total number of frames emitted.
   */
  "frame_count": number;
  /**
   * JSON shape of response headers (redacted).
   */
  "headers_shape"?: unknown;
  /**
   * Whether real network I/O was performed.
   */
  "network_performed": boolean;
  /**
   * Provider-assigned request id if available.
   */
  "provider_request_id"?: null | string;
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
  /**
   * Redaction state applied to the stream.
   */
  "redaction_state"?: RedactionState;
  /**
   * Final status: "ok", "error", "timeout", "cancelled".
   */
  "status": string;
  /**
   * HTTP status code if available.
   */
  "status_code"?: null | number;
}

/**
 * Request to open a WebSocket connection.
 */
export interface OutboundWebSocketOpenRequest {
  "capability_id": string;
  "destination_host": string;
  "max_duration_ms": number;
  "max_frame_bytes": number;
  "max_idle_ms": number;
  "max_total_bytes_inbound": number;
  "max_total_bytes_outbound": number;
  "metadata": unknown;
  "package_id": string;
  "path"?: null | string;
  "purpose"?: null | string;
  "secret_headers": Record<string, string>;
  "secret_refs": Array<string>;
  /**
   * Pre-resolved headers (raw); secrets injected in handshake. Static-only.
   */
  "static_headers": Record<string, string>;
  "subprotocols": Array<string>;
}

export interface OutboundWebSocketSendParams {
  "bytes"?: Array<number> | null;
  "code"?: null | number;
  "connection_id": string;
  "data"?: null | string;
  "kind"?: FrameKind | null;
  "reason"?: null | string;
}

export interface PackageAuditReport {
  "declared": DeclaredAuthority;
  "package_id": string;
  "since": string;
  "suggestions": Array<TighteningSuggestion>;
  "until": string;
  "unused": UnusedAuthority;
  "used": UsedAuthority;
}

export interface PackageContributions {
  "extension_points"?: Array<ExtensionPointDescriptor>;
  "hooks"?: Array<HookSubscription>;
  "schemas"?: Array<SchemaContribution>;
  "surfaces"?: Array<SurfaceContribution>;
}

export interface PackageDependency {
  /**
   * Logical package id (must match the dependency's manifest.id once resolved)
   */
  "id": string;
  /**
   * Optional: GPG public key fingerprints required to sign this dep If empty, no signature verification required If set, the dep's GPG-signed tag must be signed by one of these
   */
  "minimum_signed_by"?: Array<string>;
  /**
   * Where the package comes from
   */
  "source": DependencySource;
  /**
   * Semver constraint (e.g., ">=1.0.0", "^2.1", "=1.2.3") Empty string means "any version"
   */
  "version"?: string;
}

export interface PackageEnvelopeDescriptor {
  "artifact": ArtifactDescriptor;
  "artifacts"?: Array<NamedPackageArtifact>;
  "components": Array<ComponentDescriptor>;
  "content_roots"?: Array<ArtifactDescriptor>;
  "manifest": ArtifactDescriptor;
  "package_id": string;
  "package_version": string;
  "protocols"?: Array<PackagedProtocolDescriptor>;
  "surfaces"?: Array<PackagedSurfaceDescriptor>;
}

export interface PackageFailureSummary {
  "exit_code"?: null | string;
  "failed_at": string;
  "log_tail_redacted": Array<SubprocessLogLine>;
  "package_id": string;
  "reason": string;
  "redaction_state": RedactionState;
  "signal"?: null | string;
  "state": PackageState;
  "stderr_tail_redacted": Array<string>;
  "stderr_truncated": boolean;
}

export interface PackageIdParams {
  "package_id": string;
}

export interface PackageLifecyclePayload {
  "capability_count": number;
  /**
   * Contract mode selected by the package entry. `none` marks Path B: a self-contained app hosted without contract enforcement.
   */
  "contract_mode": ContractMode;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "package_id": string;
  "reason"?: null | string;
  "state": string;
  "version": string;
}

export interface PackageManifest {
  "author"?: null | string;
  "consumes"?: Array<CapabilityRequirement>;
  "contributes"?: PackageContributions;
  "description"?: null | string;
  "display_name"?: null | string;
  "entry": EntryDescriptor;
  "id": string;
  "license"?: null | string;
  "permissions"?: PermissionSet;
  "provides"?: Array<CapabilityDescriptor>;
  /**
   * First-class package dependency declarations. Distinct from `consumes` (which declares capability requirements). Empty by default for backward compat.
   */
  "requires"?: Array<PackageDependency>;
  "sandbox_policy"?: SandboxPolicy;
  "schema_version": number;
  "version": string;
}

export interface PackagePermissions {
  "call"?: Array<string>;
}

export interface PackageRecord {
  "capability_count": number;
  "components"?: Array<ComponentDescriptor>;
  "enforced_boundaries"?: ComponentBoundaryClaims;
  "entry_kind": string;
  "extension_point_count": number;
  "hook_count": number;
  "id": string;
  "last_failure"?: PackageFailureSummary | null;
  "loaded_at": string;
  "manifest": PackageManifest;
  "package_envelope"?: PackageEnvelopeDescriptor | null;
  "state": PackageState;
  /**
   * Canonical Contract v2 trust classification. Unlike `trust_level`, this distinguishes `contract:none` as a foreign capsule.
   */
  "trust_class"?: ComponentTrustClass;
  "trust_level": TrustLevel;
  "updated_at": string;
  "version": string;
}

export type PackageState = "discovered" | "loading" | "starting" | "ready" | "degraded" | "stopping" | "stopped" | "unloaded";

export interface PackagedProtocolDescriptor {
  "artifact": ArtifactDescriptor;
  "implementation": ProtocolImplementationDeclaration;
}

export interface PackagedSurfaceDescriptor {
  "artifact": ArtifactDescriptor;
  "surface_id": string;
  "version": string;
}

export interface PermissionGrantParams {
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "scope"?: null | string;
}

export interface PermissionGrantRecord {
  "granted_at": string;
  "id": string;
  "permission": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
  "revoked_at"?: null | string;
  "scope"?: null | string;
}

export interface PermissionListParams {
  "principal"?: ProtocolPrincipal | null;
}

export interface PermissionRevokeParams {
  "grant_id": string;
}

export interface PermissionSet {
  "assets"?: AssetPermissions;
  "capabilities"?: CapabilityPermissions;
  "events"?: EventPermissions;
  "filesystem"?: FilesystemPermissions;
  "local_exec"?: LocalExecPermissions;
  "network"?: NetworkPermissions;
  "packages"?: PackagePermissions;
  "ports"?: PortPermissions;
  "proxy"?: ProxyPermissions;
  /**
   * Declared secret references this package may use in `host.outbound.execute` calls. Each entry must be a valid env-backed secret reference (e.g. `secret_ref:env:OPENAI_API_KEY`, `secretRef:env:MY_KEY`, `secret-ref:env:NAME`, `host:env:NAME`). The runtime enforces fail-closed: any `secret_ref` used in `secret_headers` or top-level `secret_refs` at dispatch time **must** appear in this list, or the request is denied. Default: empty vec (no secret refs allowed; backward compatible).
   */
  "secret_refs"?: Array<string>;
}

export interface PlacementConstraint {
  "constraint_id": string;
  "hard": boolean;
  "kind": PlacementConstraintKind;
  "label"?: null | string;
  "nodes"?: Array<NodeId>;
  "value"?: null | string;
}

export type PlacementConstraintKind = "co_locate" | "separate" | "require_label" | "prefer_label";

export interface PolicyDecision {
  "change_set_id": string;
  "decided_at": string;
  "decision_type_uri"?: string;
  "evaluated_authority"?: Array<string>;
  "id": string;
  "outcome": PolicyDecisionOutcome;
  "policy_ref"?: ArtifactDescriptor | null;
  "principal": PrincipalIdentity;
  "reason"?: null | string;
}

export type PolicyDecisionOutcome = "allowed" | "denied" | "requires_approval";

export type PortBindScope = "loopback_only";

export interface PortContract {
  "interface_id": string;
  "profiles"?: Array<string>;
  "protocol_id": string;
  "version": string;
}

export interface PortDeclaration {
  "max_count"?: null | number;
  "port_names"?: Array<string>;
  "target_id": string;
}

export interface PortDescriptor {
  "annotations"?: Record<string, unknown>;
  "contract": PortContract;
  "interaction": string;
  "port_id": PortId;
  "role": PortRole;
  "transport"?: TransportRequirements;
}

export type PortDirection = "import" | "export";

export interface PortEndpoint {
  "node_id": NodeId;
  "port_id": PortId;
}

export type PortId = string;

export interface PortLeaseIdParams {
  "lease_id": string;
}

export interface PortLeaseRecord {
  "bind": PortBindScope;
  "host": string;
  "id": string;
  "port": number;
  "port_name": string;
  "protocol": PortProtocol;
  "status": PortLeaseStatusKind;
  "target_id": string;
}

export interface PortLeaseRequest {
  "port_name": string;
  "protocol"?: PortProtocol;
  "requested_port"?: null | number;
  "target_id": string;
}

export interface PortLeaseResponse {
  "lease": PortLeaseRecord;
}

export type PortLeaseStatusKind = "active" | "reserved" | "released";

export interface PortMultiplicity {
  "max"?: null | number;
  "min": number;
}

export interface PortPermissions {
  "declarations"?: Array<PortDeclaration>;
  "max_count"?: null | number;
}

export type PortProtocol = "tcp" | "udp";

export type PortRole = {
  "accepted_effects": Array<EffectClass>;
  "availability": AvailabilityPolicy;
  "kind": "import";
  "latest_binding_phase": BindingPhase;
  "multiplicity": PortMultiplicity;
} | {
  "effect_class": EffectClass;
  "kind": "export";
  "multiplicity": PortMultiplicity;
};

export type PrincipalIdentity = {
  "assistant_id": string;
  "delegated_user_id"?: null | string;
  "kind": "assistant";
} | {
  "kind": "anonymous";
} | {
  "kind": "host_admin";
} | {
  "kind": "host_dev";
} | {
  "kind": "human";
  "user_id": string;
} | {
  "kind": "package";
  "package_id": string;
} | {
  "kind": "platform_runtime";
};

export interface ProjectionDefinition {
  "id": string;
  "session_id": string;
  "source_kind_prefix"?: null | string;
  "state"?: unknown;
}

export interface ProjectionIdParams {
  "projection_id": string;
}

export type ProjectionListResult = Array<{
  "id": string;
  "session_id": string;
  "source_kind_prefix"?: null | string;
  "state"?: unknown;
}>;

export interface ProposalApproval {
  "decided_at": string;
  "principal": ProtocolPrincipal;
  "reason"?: null | string;
}

export interface ProposalDecisionParams {
  "proposal_id": string;
  "reason"?: null | string;
}

export interface ProposalIdParams {
  "proposal_id": string;
}

export interface ProposalOperation {
  "op": string;
  "payload"?: unknown;
  "target"?: null | string;
}

export interface ProposalRecord {
  "approval"?: ProposalApproval | null;
  "change_set"?: ChangeSet | null;
  "commit"?: ChangeCommit | null;
  "created_at"?: string;
  "created_by"?: ProtocolPrincipal;
  "expected_effects"?: unknown;
  "id"?: string;
  "intent"?: Intent | null;
  "operations"?: Array<ProposalOperation>;
  "policy_decision"?: PolicyDecision | null;
  "receipt"?: ArtifactDescriptor | null;
  "required_permissions"?: Array<string>;
  "result"?: unknown;
  "status"?: ProposalStatus;
  "target_branch_id"?: null | string;
  "target_session_id"?: null | string;
}

export type ProposalStatus = "created" | "approved" | "applying" | "rejected" | "applied" | "partial" | "failed";

export interface ProtocolAuthorityContext {
  "actions"?: Array<string>;
  "delegation_chain"?: Array<string>;
  "grant_id": string;
  "resources"?: Array<ProtocolResourceSelector>;
}

export interface ProtocolAuthorityRequirement {
  "authority": string;
  "operations": Array<string>;
  "scope": string;
}

export interface ProtocolCompatibilityProfile {
  "description": string;
  "id": string;
  "maturity": ProtocolMaturity;
  "version": string;
}

export interface ProtocolConformanceVector {
  "description": string;
  "id": string;
  "profiles"?: Array<string>;
  "required": boolean;
}

export interface ProtocolContext {
  /**
   * Authenticated Host authority carried by transport adapters. This is additive so older callers remain source- and wire-compatible. Device calls use the existing anonymous V1 principal as a fail-closed sentinel: old runtimes ignore this field and deny the call, while new runtimes require the scoped authority below.
   */
  "authority"?: ProtocolAuthorityContext | null;
  "correlation_id"?: null | string;
  "host_operation"?: ProtocolHostOperationContext | null;
  "parent_invocation_id"?: null | string;
  "principal": ProtocolPrincipal;
  /**
   * Optional kernel session id this call is operating under. Used by outbound dispatch to scope secret resolution to the session's Installation.
   */
  "session_id"?: null | string;
  "transport": string;
}

export interface ProtocolDescriptor {
  "authority_requirements"?: Array<ProtocolAuthorityRequirement>;
  "compatibility_profiles": Array<ProtocolCompatibilityProfile>;
  "conformance_vectors": Array<ProtocolConformanceVector>;
  "conforming_implementations"?: Array<ProtocolImplementationClaim>;
  "descriptor_type_uri": string;
  "error_model": ProtocolDocumentReference;
  "lifecycle": ProtocolDocumentReference;
  "maturity": ProtocolMaturity;
  "migrations"?: Array<ProtocolMigration>;
  "protocol_id": string;
  "schemas": Array<ProtocolSchemaReference>;
  "semantic_specification": ProtocolDocumentReference;
  "version": string;
  "wit_worlds"?: Array<ProtocolSchemaReference>;
}

export interface ProtocolDocumentReference {
  "digest"?: null | string;
  "media_type": string;
  "uri": string;
}

export interface ProtocolError {
  "code": string;
  "details"?: unknown;
  "message": string;
}

export type ProtocolExtensionDescribeResult = null;

export type ProtocolExtensionListResult = Array<string>;

export type ProtocolHookListResult = Array<{
  "subscriber_package_id": string;
  "subscription": HookSubscription;
}>;

/**
 * Request-specific Host operation facts established by a trusted transport adapter after it has parsed and authorized the request. Unlike authority, this is never populated from the request body itself.
 */
export interface ProtocolHostOperationContext {
  "action": string;
  "resources"?: Array<ProtocolResourceSelector>;
}

export interface ProtocolImplementationClaim {
  "conformance_vectors": Array<string>;
  "implementation_id": string;
  "profiles": Array<string>;
  "provider": string;
  "test_only"?: boolean;
  "version": string;
}

export interface ProtocolImplementationDeclaration {
  "conformance_vectors"?: Array<string>;
  "profiles"?: Array<string>;
  "protocol_id": string;
  "version": string;
}

export type ProtocolMaturity = "experimental" | "candidate" | "stable" | "deprecated";

export interface ProtocolMethod {
  "id": string;
  "status": MethodStatus;
  "streaming": boolean;
}

export interface ProtocolMigration {
  "adapter_id": string;
  "from_protocol_id": string;
  "from_version": string;
  "instructions": ProtocolDocumentReference;
  "kind": ProtocolMigrationKind;
  "lossless": boolean;
  "to_version": string;
}

export type ProtocolMigrationKind = "identity_adapter" | "semantic_adapter" | "data_migration";

export type ProtocolPrincipal = {
  "assistant_id": string;
  "delegated_user_id"?: null | string;
  "kind": "assistant";
} | {
  "kind": "anonymous";
} | {
  "kind": "host_admin";
} | {
  "kind": "host_dev";
} | {
  "kind": "human";
  "user_id": string;
} | {
  "kind": "package";
  "package_id": string;
};

export interface ProtocolProfilePin {
  "profile": string;
  "protocol_id": string;
  "version": string;
}

export interface ProtocolRequirement {
  "profiles"?: Array<string>;
  "protocol_id": string;
  "version": string;
}

export interface ProtocolResourceSelector {
  /**
   * An explicit null selects every resource of this owner/kind. Omitting the field is invalid. Resource matching is structural and exact; callers must never use string-prefix matching for authority decisions.
   */
  "id": string;
  "kind": string;
  "owner": string;
}

export interface ProtocolResponse {
  "error"?: ProtocolError | null;
  "id": string;
  "result"?: unknown;
}

export type ProtocolSchemaKind = "json_schema" | "wit_world" | "other";

export interface ProtocolSchemaReference {
  "id": string;
  "kind": ProtocolSchemaKind;
  "uri": string;
  "version": string;
}

export interface ProtocolSelection {
  "profile"?: null | string;
  "protocol_id": string;
  "version": string;
}

export interface ProxyDeclaration {
  "max_count"?: null | number;
  "route_ids"?: Array<string>;
}

export interface ProxyPermissions {
  "declarations"?: Array<ProxyDeclaration>;
  "max_count"?: null | number;
}

export type ProxyProtocol = "http" | "websocket";

export type ProxyRouteAccess = "host_authenticated" | "public";

export interface ProxyRouteIdParams {
  "route_id": string;
}

export interface ProxyRouteRecord {
  "access"?: ProxyRouteAccess;
  "id": string;
  "iframe_url": string;
  "protocol": ProxyProtocol;
  "public_url": string;
  "ready": boolean;
  "status": ProxyRouteStatusKind;
  "upstream": ProxyRouteUpstream;
}

export interface ProxyRouteRegisterRequest {
  "access"?: ProxyRouteAccess;
  "protocol"?: ProxyProtocol;
  "route_id"?: null | string;
  "upstream": ProxyRouteUpstream;
}

export interface ProxyRouteRegisterResponse {
  "route": ProxyRouteRecord;
}

export type ProxyRouteStatusKind = "active" | "stale" | "removed";

export interface ProxyRouteUpstream {
  "port_lease_id": string;
  "port_name": string;
}

export interface ReadinessProbe {
  "initial_delay_ms"?: null | number;
  "kind": ReadinessProbeKind;
  "path"?: null | string;
  "port_name"?: null | string;
  "timeout_ms"?: null | number;
}

export type ReadinessProbeKind = "none" | "tcp_port" | "http_get";

export interface RealizationApplyRequest {
  "approval": RealizationApproval;
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "plan_ref": ArtifactDescriptor;
  "realization_id": RealizationId;
  "target_id": string;
}

export interface RealizationApproval {
  "accepted_risks"?: Array<string>;
  "decided_at": string;
  "decision": string;
  "expires_at"?: null | string;
  "plan_digest": string;
}

export type RealizationBackendSelection = {
  "build_context_ref": ArtifactDescriptor;
  "build_descriptor_hash": string;
  "container_port": number;
  "dockerfile": string;
  "execution_class": string;
  "health_path"?: null | string;
  "kind": "docker_build";
  "network_mode": ManagedTargetBuildNetworkMode;
  "port_name": string;
  "route_access"?: ProxyRouteAccess;
  "route_id": string;
  "source_tree_digest": string;
  "workload_id": string;
  "workspace_id": WorkspaceId;
} | {
  "container_port": number;
  "execution_class": string;
  "health_path"?: null | string;
  "image": string;
  "kind": "oci_image";
  "port_name": string;
  "pull_if_missing"?: boolean;
  "route_access"?: ProxyRouteAccess;
  "route_id": string;
  "workload_id": string;
};

export interface RealizationGetRequest {
  "installation_id": InstallationId;
  "realization_id": RealizationId;
}

export interface RealizationHealth {
  "evidence_refs"?: Array<ArtifactDescriptor>;
  "reason_code"?: null | string;
  "status": HealthStatus;
}

export type RealizationId = string;

export interface RealizationLifecyclePayloadSchema {
  "operation": string;
  "realization": RealizationRevision;
  "reason_code"?: null | string;
  "target_id": string;
}

export interface RealizationListRequest {
  "installation_id"?: InstallationId | null;
  "target_id"?: null | string;
}

export interface RealizationMutationResult {
  "gaps"?: Array<RealizationPlanningGap>;
  "realization": RealizationRevision;
  "replayed": boolean;
}

export interface RealizationPlan {
  "assembly_lock": ArtifactDescriptor;
  "build_actions"?: Array<BuildAction>;
  "endpoint_actions"?: Array<EndpointAction>;
  "installation_id": InstallationId;
  "inventory_refs": Array<ArtifactDescriptor>;
  "launch_actions"?: Array<LaunchAction>;
  "operational_intent": ArtifactDescriptor;
  "placements"?: Array<NodePlacement>;
  "preconditions"?: Array<ChangePrecondition>;
  "required_authority": Array<string>;
  "risk_summary"?: Array<string>;
  "schema": "plurora.realization-plan.v1";
  "state_actions"?: Array<StateAction>;
  "transports"?: Array<TransportBindingPlan>;
  "work_revision": ArtifactDescriptor;
}

export interface RealizationPlanRequest {
  "backends": Array<RealizationBackendSelection>;
  "expected_installation_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "target_id": string;
}

export interface RealizationPlanResult {
  "gaps"?: Array<RealizationPlanningGap>;
  "plan"?: RealizationPlan | null;
  "plan_ref"?: ArtifactDescriptor | null;
  "realization"?: RealizationRevision | null;
  "replayed": boolean;
}

export interface RealizationPlanningGap {
  "next_step": string;
  "reason_code": string;
  "target_id"?: null | string;
  "workload_id"?: null | string;
}

export interface RealizationReconcileRequest {
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "realization_id": RealizationId;
  "target_id": string;
}

export interface RealizationRevision {
  "activated_at"?: null | string;
  "actual_resources"?: Array<RealizedResource>;
  "created_at": string;
  "health": RealizationHealth;
  "installation_id": InstallationId;
  "parent_realization_id"?: RealizationId | null;
  "plan_ref": ArtifactDescriptor;
  "realization_id": RealizationId;
  "receipts"?: Array<ArtifactDescriptor>;
  "revision": number;
  "status": RealizationStatus;
  "stopped_at"?: null | string;
  "updated_at": string;
}

export interface RealizationRollbackRequest {
  "approval": RealizationApproval;
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "realization_id": RealizationId;
  "rollback_to_realization_id": RealizationId;
  "target_id": string;
}

export type RealizationStatus = "planned" | "applying" | "active" | "degraded" | "stopping" | "stopped" | "failed" | "outcome_unknown" | "recovery_required";

export interface RealizationStopRequest {
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "realization_id": RealizationId;
  "target_id": string;
}

export interface RealizedResource {
  "backend_id": string;
  "properties"?: Record<string, unknown>;
  "receipt_ref"?: ArtifactDescriptor | null;
  "resource_id": string;
  "resource_type": string;
  "target_id": string;
}

/**
 * Redaction state for an outbound audit record.
 *
 * Every outbound request carries one of these states to indicate whether raw body/header/prompt/response data was preserved. The default is `NotCaptured` — raw data is never saved unless explicitly approved.
 */
export type RedactionState = "explicitly_approved" | "not_captured" | "policy_ref" | "redacted" | "unsafe_blocked";

export interface RemoteAuth {
  "config"?: unknown;
  "scheme": string;
}

export interface ReplicaPolicy {
  "max": number;
  "min": number;
}

export interface ResolvedPortPin {
  "canonical_contract_digest": string;
  "leaf_port": PortEndpoint;
  "node_path": Array<NodeId>;
  "root_port": PortId;
}

export interface ResourceCapacity {
  "cpu_millis"?: number;
  "gpu_count"?: number;
  "max_workloads"?: number;
  "memory_bytes"?: number;
  "storage_bytes"?: number;
}

export interface ResourceRequirements {
  "cpu_millis"?: null | number;
  "duration_seconds"?: null | number;
  "gpu_count"?: null | number;
  "max_concurrency"?: null | number;
  "memory_bytes"?: null | number;
  "storage_bytes"?: null | number;
}

export interface ResourceSelector {
  "id": string;
  "kind": string;
}

export type RestartPolicy = "never" | "on_failure" | "always";

export type RightDisposition = "allowed" | "denied" | "requires_entitlement" | "unspecified";

export interface RightsDeclaration {
  "backup": RightDisposition;
  "copy_across_hosts": RightDisposition;
  "dedicated_server": RightDisposition;
  "derive": RightDisposition;
  "entitlement_requirements"?: Array<ProtocolRequirement>;
  "evidence_refs"?: Array<ArtifactDescriptor>;
  "execute": RightDisposition;
  "export_state": RightDisposition;
  "install": RightDisposition;
  "license_expression"?: null | string;
  "modding": RightDisposition;
  "modify": RightDisposition;
  "redistribute_artifacts": RightDisposition;
  "terms_uri"?: null | string;
}

export interface RunEntrypointPreflight {
  "entrypoint_id": string;
  "gaps": Array<RunGap>;
}

export interface RunGap {
  "next_step": string;
  "node_id"?: null | string;
  "port_id"?: null | string;
  "reason_code": string;
}

export interface RunGetRequest {
  "installation_id": InstallationId;
  "run_id": RunId;
}

export interface RunHealth {
  "diagnostic_refs"?: Array<ArtifactDescriptor>;
  "reason_code"?: null | string;
  "status": HealthStatus;
}

export type RunId = string;

export interface RunLifecyclePayloadSchema {
  "run": RunView;
}

export interface RunListRequest {
  "installation_id"?: InstallationId | null;
  "status"?: RunStatus | null;
}

export interface RunMutationResult {
  "idempotent": boolean;
  "run": RunView;
}

export interface RunRecord {
  "bindings"?: Array<ActiveBindingRecord>;
  "context_id"?: null | string;
  "health": RunHealth;
  "installation_id": InstallationId;
  "node_instances"?: Array<NodeInstanceRecord>;
  "run_id": RunId;
  "started_at": string;
  "status": RunStatus;
  "stopped_at"?: null | string;
}

/**
 * Exact Run identity established by the Host. The three fields are one optional unit: Launch-time selection can omit the entire value, while a Runtime selection must carry all of it.
 */
export interface RunRevisionPin {
  "context_id": string;
  "run_id": RunId;
  "run_revision": number;
}

export interface RunStartRequest {
  "entrypoint_id": string;
  "expected_installation_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
}

export interface RunStartResult {
  "gaps"?: Array<RunGap>;
  "idempotent": boolean;
  "run"?: RunView | null;
}

export type RunStatus = "starting" | "running" | "degraded" | "stopping" | "stopped" | "failed" | "interrupted";

export interface RunStatusRequest {
  "entrypoint_id"?: null | string;
  "installation_id": InstallationId;
}

export interface RunStatusView {
  "active_run"?: RunView | null;
  "installation_id": InstallationId;
  "installation_revision": number;
  "preflight"?: RunEntrypointPreflight | null;
  "work_revision": ArtifactDescriptor;
}

export interface RunStopRequest {
  "expected_revision": number;
  "idempotency_key": string;
  "installation_id": InstallationId;
  "run_id": RunId;
}

export interface RunView {
  "entrypoint_id": string;
  "installation_revision": number;
  "record": RunRecord;
  "revision": number;
}

export interface SandboxPolicy {
  "cpu_quota_ms_per_invoke"?: number;
  "memory_mb"?: number;
  "wall_clock_ms"?: number;
}

export interface SchemaContribution {
  "id": string;
  "schema": unknown;
}

export interface SecretImport {
  "required"?: boolean;
  "secret_id": string;
}

export interface SelectedTransport {
  "class_id": string;
  "properties"?: Record<string, unknown>;
}

export interface SessionBranchListParams {
  "session_id": string;
}

export interface SessionCloseParams {
  "session_id": string;
}

export interface SessionForkParams {
  "forked_from_sequence": number;
  "metadata": unknown;
  "parent_session_id": string;
}

export interface SessionGetParams {
  "session_id": string;
}

export interface SessionRecord {
  "active_package_set": Array<string>;
  "created_at": string;
  "id": string;
  "labels": Array<string>;
  "metadata"?: unknown;
  "principal_scope"?: null | string;
  "status": SessionStatus;
  "updated_at": string;
}

export type SessionStatus = "open" | "closed";

export type ShellContributionDescribeResult = Record<string, unknown>;

export type ShellContributionListResult = Array<unknown>;

export type SourceVisibility = "open" | "source_available" | "closed" | "unknown";

export interface StateAction {
  "action_id": string;
  "input_ref"?: ArtifactDescriptor | null;
  "kind": StateActionKind;
  "state_slot_id": StateSlotId;
  "target_id": string;
}

export type StateActionKind = "provision" | "attach" | "snapshot" | "restore" | "migrate";

export type StateBindingKind = "host_managed" | "external_provider";

export interface StateBindingRecord {
  "binding_id": string;
  "kind": StateBindingKind;
  "provider_ref"?: ArtifactDescriptor | null;
  "state_slot_id": StateSlotId;
}

export type StateDisposition = "keep" | "delete";

export type StateDurability = "ephemeral" | "durable" | "external";

export interface StatePlacementIntent {
  "durability": StateDurability;
  "replication"?: number;
  "required_capabilities"?: Array<string>;
  "state_slot_id": StateSlotId;
}

export type StatePortability = "portable" | "opaque_exportable" | "host_bound" | "external_authority";

export type StateScope = "run" | "installation" | "user" | "shared" | "external";

export interface StateSlotDescriptor {
  "annotations"?: Record<string, unknown>;
  "backup_policy": BackupPolicy;
  "migration_port"?: PortEndpoint | null;
  "owner_node_id": NodeId;
  "portability": StatePortability;
  "schema_ref"?: ArtifactDescriptor | null;
  "scope": StateScope;
  "state_slot_id": StateSlotId;
}

export type StateSlotId = string;

/**
 * The format of a streaming response for `host.outbound.stream`.
 */
export type StreamFormat = "ndjson" | "raw" | "sse";

/**
 * Generic stream frame envelope — the unit of streaming capability output.
 *
 * This is a content-free protocol shape. It carries invocation/stream identifiers, sequencing, and redaction state, but no model, prompt, agent, or message semantics. The `payload` field is opaque JSON controlled by the capability provider.
 */
export interface StreamFrameEnvelope {
  /**
   * Frame type discriminant.
   */
  "frame_type": StreamFrameType;
  /**
   * The invocation this frame belongs to.
   */
  "invocation_id": string;
  /**
   * Opaque metadata — capability-provider-defined.
   */
  "metadata"?: unknown;
  /**
   * Opaque payload — capability-provider-defined; no kernel content semantics. May be `Null` for progress/end/cancelled/timeout frames.
   */
  "payload"?: unknown;
  /**
   * Redaction state applied to the payload.
   */
  "redaction_state"?: RedactionState;
  /**
   * Monotonically increasing sequence within this stream.
   */
  "sequence": number;
  /**
   * Unique stream id (may differ from invocation_id if a capability produces multiple concurrent streams).
   */
  "stream_id": string;
  /**
   * Timestamp of frame emission.
   */
  "timestamp"?: string;
}

/**
 * Generic stream frame envelope — the unit of streaming capability output.
 *
 * This is a content-free protocol shape. It carries invocation/stream identifiers, sequencing, and redaction state, but no model, prompt, agent, or message semantics. The `payload` field is opaque JSON controlled by the capability provider.
 */
export interface StreamFrameEnvelope2 {
  /**
   * Frame type discriminant.
   */
  "frame_type": StreamFrameType;
  /**
   * The invocation this frame belongs to.
   */
  "invocation_id": string;
  /**
   * Opaque metadata — capability-provider-defined.
   */
  "metadata"?: unknown;
  /**
   * Opaque payload — capability-provider-defined; no kernel content semantics. May be `Null` for progress/end/cancelled/timeout frames.
   */
  "payload"?: unknown;
  "receipt"?: null | {
  "annotations"?: Record<string, unknown>;
  "artifact_type_uri": string;
  "digest": string;
  "media_type": string;
  "references"?: Array<string>;
  "size_bytes": number;
};
  /**
   * Redaction state applied to the payload.
   */
  "redaction_state"?: RedactionState;
  /**
   * Monotonically increasing sequence within this stream.
   */
  "sequence": number;
  /**
   * Unique stream id (may differ from invocation_id if a capability produces multiple concurrent streams).
   */
  "stream_id": string;
  /**
   * Timestamp of frame emission.
   */
  "timestamp"?: string;
}

/**
 * The type of a stream frame — content-free, no model/prompt semantics.
 */
export type StreamFrameType = "cancelled" | "chunk" | "end" | "error" | "progress" | "start" | "timeout";

/**
 * Status returned when a streaming outbound request starts.
 */
export type StreamStartStatus = "denied" | "error" | "ok";

export interface SubprocessLogLine {
  "line": string;
  "package_id": string;
  "stream": string;
}

export type SubprocessTransport = "json_rpc_stdio" | "json_rpc_tcp";

export interface SurfaceActivation {
  "input_schema"?: unknown;
  "launch_capability_id"?: null | string;
  "session_template"?: unknown;
}

export type SurfaceApprovalPolicy = "none" | "user_approval" | "fork_then_approve";

export type SurfaceBundleSourceSchema = "package" | "dev_path";

export interface SurfaceContribution {
  "activation"?: SurfaceActivation;
  /**
   * Additional exact capability ids this surface bundle may invoke through the web surface bridge. This is a typed declaration; bridge policy must not infer invoke authority from opaque metadata.
   */
  "allowed_capability_ids"?: Array<string>;
  "approval_policy"?: SurfaceApprovalPolicy | null;
  "capability_id"?: null | string;
  "description"?: null | string;
  "id": string;
  "metadata"?: unknown;
  "required_permissions"?: Array<SurfacePermissionRequirement>;
  "slot": SurfaceSlot;
  "title": string;
  "version"?: string;
}

export interface SurfaceDescribeParams {
  "surface_id": string;
}

export interface SurfaceListParams {
  "slot"?: null | string;
}

export interface SurfacePermissionRequirement {
  "permission": string;
  "reason"?: null | string;
  "risk"?: SurfaceRisk;
  "scope"?: null | string;
}

export interface SurfaceResolveBundleParams {
  "surface_id": string;
}

export interface SurfaceResolveBundleResult {
  "bundle_fingerprint"?: null | string;
  "bundle_url": string;
  "export_name": string;
  "package_id"?: null | string;
  "source": SurfaceBundleSourceSchema;
  "stylesheets": Array<string>;
  "surface_id": string;
  "wrapper_class"?: null | string;
}

export type SurfaceRisk = "low" | "medium" | "high";

export type SurfaceSlot = "experience_entry" | "home_card" | "quick_action" | "workshop_card" | "play_renderer" | "forge_panel" | "asset_editor" | "assistant_action";

export interface TargetCapabilityRecord {
  "available": boolean;
  "capability_id": string;
  "evidence_refs"?: Array<ArtifactDescriptor>;
  "properties"?: Record<string, unknown>;
  "version": string;
}

export interface TargetIdParams {
  "target_id": string;
}

export interface TargetInventorySnapshot {
  "capabilities"?: Array<TargetCapabilityRecord>;
  "capacity"?: ResourceCapacity;
  "labels"?: Record<string, string>;
  "observed_at": string;
  "target_id": string;
  "topology"?: Array<TopologyRelation>;
  "trust_zone": string;
}

export interface TighteningSuggestion {
  "kind": string;
  "rationale": string;
  "target": string;
}

export interface TopologyRelation {
  "latency_class"?: null | string;
  "other_target_id": string;
  "properties"?: Record<string, unknown>;
  "relation_id": string;
}

export interface TransparencyDeclaration {
  "evidence_refs"?: Array<ArtifactDescriptor>;
  "provenance_refs"?: Array<ArtifactDescriptor>;
  "reproducible_build_claim": ClaimStatus;
  "sbom_refs"?: Array<ArtifactDescriptor>;
  "signature_refs"?: Array<ArtifactDescriptor>;
  "source_refs"?: Array<ArtifactDescriptor>;
  "source_visibility": SourceVisibility;
  "state_portability": StatePortability;
  "telemetry_disclosures"?: Array<string>;
}

export interface TransportBindingPlan {
  "binding_id": string;
  "consumer": PortEndpoint;
  "consumer_target_id": string;
  "phase": BindingPhase;
  "provider": PortEndpoint;
  "provider_target_id": string;
  "transport": SelectedTransport;
}

export interface TransportPolicy {
  "preferred_classes"?: Array<string>;
  "requirements"?: TransportRequirements;
}

export interface TransportRequirements {
  "allowed_classes"?: Array<string>;
  "extensions"?: Record<string, unknown>;
  "large_payload"?: boolean;
  "local_only"?: boolean;
  "max_latency_class"?: null | string;
  "ordered"?: boolean;
  "reliable"?: boolean;
  "same_process"?: boolean;
  "shared_memory_allowed"?: boolean;
}

export type TrustLevel = "trusted_inproc" | "process_isolated" | "wasm_sandbox" | "remote_boundary" | "static_surface";

export interface UnusedAuthority {
  "capabilities_unused": Array<string>;
  "network_hosts_unused": Array<string>;
  "secret_refs_unused": Array<string>;
}

export interface UpdatePolicy {
  "health_timeout_seconds"?: null | number;
  "max_unavailable"?: number;
  "strategy": UpdateStrategy;
}

export type UpdateStrategy = "replace" | "rolling" | "recreate";

export interface UsedAuthority {
  "assets_read_count": number;
  "assets_write_count": number;
  "capabilities_invoked": Record<string, number>;
  "events_append_count": number;
  "events_read_count": number;
  "network_hosts_used": Record<string, number>;
  "secret_refs_used": Record<string, number>;
}

export interface WorkEntrypoint {
  "annotations"?: Record<string, unknown>;
  "id": string;
  "intent_uri": string;
  "target": WorkEntrypointTarget;
}

export type WorkEntrypointTarget = {
  "kind": "assembly_port";
  "port_id": PortId;
} | {
  "kind": "foreign_launch";
  "launch_id": string;
} | {
  "kind": "surface";
  "surface_id": string;
};

export type WorkId = string;

export interface WorkRevision {
  "annotations"?: Record<string, unknown>;
  "assembly": ArtifactDescriptor;
  "content_roots"?: Array<ArtifactDescriptor>;
  "description"?: string;
  "entrypoints"?: Array<WorkEntrypoint>;
  "operational_intent"?: ArtifactDescriptor | null;
  "rights"?: ArtifactDescriptor | null;
  "schema": "plurora.work-revision.v1";
  "title": string;
  "transparency"?: ArtifactDescriptor | null;
  "work_id": WorkId;
}

export interface WorkloadImports {
  "filesystem"?: Array<FilesystemImport>;
  "network"?: Array<NetworkImport>;
  "secret_imports"?: Array<SecretImport>;
}

export interface WorkloadIntent {
  "annotations"?: Record<string, unknown>;
  "execution_classes": Array<string>;
  "health_port"?: PortEndpoint | null;
  "imports"?: WorkloadImports;
  "node_id": NodeId;
  "replicas": ReplicaPolicy;
  "resources"?: ResourceRequirements;
  "restart_policy": RestartPolicy;
  "workload_id": string;
}

export type WorkspaceId = string;

export interface WorldBundleArchive {
  "archive_format": string;
  "bundle_descriptor": ArtifactDescriptor;
  "manifest": WorldBundleManifest;
  "objects": Array<WorldBundleObject>;
}

export interface WorldBundleManifest {
  "annotations"?: Record<string, unknown>;
  "assembly_lock": ArtifactDescriptor;
  "bundle_type_uri": string;
  "effect_receipts"?: Array<ArtifactDescriptor>;
  "journal_ranges": Array<WorldJournalRange>;
  "lineage": Array<WorldLineageEntry>;
  "object_descriptors": Array<ArtifactDescriptor>;
  "original_v1_envelopes": Array<ArtifactDescriptor>;
  "policy_refs"?: Array<ArtifactDescriptor>;
  "protocol_id": string;
  "protocol_profile": string;
  "protocol_profiles": Array<ProtocolProfilePin>;
  "protocol_version": string;
  "schema_version": number;
  "world_head": ArtifactDescriptor;
  "world_id": string;
}

export interface WorldBundleObject {
  "data_base64": string;
  "descriptor": ArtifactDescriptor;
}

export interface WorldHead {
  "annotations"?: Record<string, unknown>;
  "assembly_lock": ArtifactDescriptor;
  "effect_receipts"?: Array<ArtifactDescriptor>;
  "head_type_uri": string;
  "history_root": ArtifactDescriptor;
  "parent_heads"?: Array<ArtifactDescriptor>;
  "policy_root"?: ArtifactDescriptor | null;
  "protocol_profiles": Array<ProtocolProfilePin>;
  "provenance_root": ArtifactDescriptor;
  "schema_version": number;
  "state_root": ArtifactDescriptor;
  "world_id": string;
}

export interface WorldJournalRange {
  "envelope_refs": Array<ArtifactDescriptor>;
  "first_sequence": number;
  "last_sequence": number;
  "session_id": string;
}

export interface WorldLineageEntry {
  "annotations"?: Record<string, unknown>;
  "effect_receipts"?: Array<ArtifactDescriptor>;
  "head": ArtifactDescriptor;
  "parent_heads"?: Array<ArtifactDescriptor>;
  "relation": string;
}
